### ISSUE TITLE
AssertionError: Weight input has to be an identity op

### ISSUE THREAD

**Issue by andychat** [tf-coreml/tf-coreml#108]
I ran a MobilenetV1 model through tf-coreml, and got the following error:

AssertionError: Weight input has to be an identity op

Here's the op printed out:

```
140/209: Converting op name: MobilenetV1/MobilenetV1/Conv2d_5_pointwise/BatchNorm/batchnorm/mul_1 ( type:  Conv2D )
name: "MobilenetV1/Conv2d_5_pointwise/weights/read/_52__cf__52"
op: "Dequantize"
input: "MobilenetV1/Conv2d_5_pointwise/weights/read/_52__cf__52_quantized_const"
input: "MobilenetV1/Conv2d_5_pointwise/weights/read/_52__cf__52_quantized_min"
input: "MobilenetV1/Conv2d_5_pointwise/weights/read/_52__cf__52_quantized_max"
attr {
  key: "T"
  value {
    type: DT_QUINT8
  }
}
attr {
  key: "mode"
  value {
    s: "MIN_FIRST"
  }
}

Traceback (most recent call last):
  File "tf2coreml.py", line 7, in <module>
    class_labels = '/tmp/output_labels.txt')
  File "/Users/andypang/code/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 477, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "/Users/andypang/code/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 275, in _convert_pb_to_mlmodel
    convert_ops_to_layers(context)
  File "/Users/andypang/code/tf-coreml/tfcoreml/_ops_to_layers.py", line 142, in convert_ops_to_layers
    translator(op, context)
  File "/Users/andypang/code/tf-coreml/tfcoreml/_layers.py", line 130, in conv2d
    'Weight input has to be an identity op')
AssertionError: Weight input has to be an identity op
```

The last layer of the model was retrained with my own images, following the image retraining tutorial from tensorflow: https://www.tensorflow.org/tutorials/image_retraining using the architecture option "mobilenet_1.0_224_quantized".

First thought is I should avoid Dequantized by dropping the quantized option out of the model.

**Comment by andychat** [comment]
Ok, not using quantized got me past the above error, but FYI that the example in the tensorflow tutorial enables this.

**Comment by vade** [comment]
Thanks, this is super useful to know Just ran into this myself. You're apparently 6 hours head of me ;)
