### ISSUE TITLE
ModuleNotFoundError: No module named '_ops_to_layers'

### ISSUE THREAD

**Issue by tgwagner** [tf-coreml/tf-coreml#116]
after installing tf-coreml with the following

pip install -e .

I attempt to run python test_tf_converter.py

and get the following error:

>   return f(*args, **kwds)
> Traceback (most recent call last):
>   File "test_tf_converter.py", line 12, in <module>
>     import tfcoreml as tf_converter
>   File "/Users/tgwagner/fresh/tf-coreml/tfcoreml/__init__.py", line 1, in <module>
>     from ._tf_coreml_converter import convert
>   File "/Users/tgwagner/fresh/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 9, in <module>
>     from _ops_to_layers import convert_ops_to_layers
> **ModuleNotFoundError: No module named '_ops_to_layers'**

Do I need to add something to my PATH or ?

Note that _ops_to_layers.py does exist in my tf-coreml/tfcoreml directory

Thanks
Todd

**Comment by tgwagner** [comment]
responding to my own question -- I solved the answer and think others might run into this so I'm leaving it up.

I set my PYTHONPATH to the follow and I was able to get past the error.

PYTHONPATH=/Users/.../fresh/tf-coreml/:/Users/.../fresh/tf-coreml/tfcoreml:/Users/.../fresh/tf-coreml/tfcoreml/optimizations
