### ISSUE TITLE
Python 3 issue - TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by jonas-arkulpa** [tf-coreml/tf-coreml#134]
We've an issue related to Python 3.
I'm able to convert my model with Python 2.7 but not with 3.6.
As it is working with Python 2 a fix isn't urgent for us.

Conversion script:
```python
import sys
import os
import tfcoreml as tf_converter

name = os.path.basename(sys.argv[1])
mlmodel_name = "%s.mlmodel" % os.path.splitext(name)[0]

tf_converter.convert(tf_model_path = sys.argv[1],
                    mlmodel_path = mlmodel_name,
                    output_feature_names = ['output:0'],
                    is_bgr = False,
                    input_name_shape_dict = {'input:0' : [1, 416, 416, 3]},
                    image_input_names = ['input:0'],
                    image_scale = 1 / 255.0)
```
```shell
python tf2coreml.py model.pb
```

The following error occurs if I try it with Python 3:
```shell
Traceback (most recent call last):
  File "tf2coreml.py", line 15, in <module>
    image_scale = 1 / 255.0)
  File ".../tf-coreml/tfcoreml/_tf_coreml_converter.py", line 483, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File ".../tf-coreml/tfcoreml/_tf_coreml_converter.py", line 285, in _convert_pb_to_mlmodel
    optimize_nn_spec(builder=builder)
  File ".../tf-coreml/tfcoreml/optimizations/_optimize_nn_spec.py", line 44, in optimize_nn_spec
    _optimize_fold_load_constants(builder.nn_spec.layers)
  File ".../tf-coreml/tfcoreml/optimizations/_optimize_nn_spec.py", line 12, in _optimize_fold_load_constants
    _optimize._fold_constants(nn_layers)
  File ".../tf-coreml/tfcoreml/optimizations/_optimize.py", line 187, in _fold_constants
    _replace_with_load_constant(nn_layers, i, y, shape, load_constant_outputs)
  File ".../tf-coreml/tfcoreml/optimizations/_optimize.py", line 124, in _replace_with_load_constant
    nn_layers[ind].loadConstant.MergeFromString('')
TypeError: a bytes-like object is required, not 'str'
```
System: Ubuntu 17.10
Built from current master: https://github.com/tf-coreml/tf-coreml/commit/e8db7a836c1c8164ebdc9e37738db8e00cf2537f
with: pip install -e .

**Comment by aseemw** [comment]
@jonas-arkulpa Can you check in PR #135 resolves this issue.

**Comment by jonas-arkulpa** [comment]
@aseemw Thanks for the fast fix. Works perfect with this change.
