### ISSUE TITLE
Input is a placeholder with incomplete shape (?, ?, ?, 3)

### ISSUE THREAD

**Issue by bowsplinter** [tf-coreml/tf-coreml#139]
I am trying to convert [this model](https://github.com/ildoonet/tf-pose-estimation/blob/master/models/graph/mobilenet_thin/graph_freeze.pb) to coreml.

This is the script I am using to convert:
```
import tfcoreml as tf_converter
tf_converter.convert(
    tf_model_path = 'models/graph/mobilenet_thin/graph_freeze.pb',
    mlmodel_path = 'my_model.mlmodel',
    output_feature_names = ['import/Openpose/concat_stage7:0'],
    input_name_shape_dict={"input:0":[1,224,224,3]},
    image_input_names=["import/input"]
)
```

I get the error:

```
2018-03-04 18:31:23.604515: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "tf2coreml.py", line 7, in <module>
    image_input_names=["import/input"]
  File "/Users/vivek/personal/experimental/tf-pose-estimation/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 483, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "/Users/vivek/personal/experimental/tf-pose-estimation/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 180, in _convert_pb_to_mlmodel
    "%s is a placeholder with incomplete shape %s" %(input_name, str(shape)))
AssertionError: image:0 is a placeholder with incomplete shape (?, ?, ?, 3)
```

Appreciate any help towards fixing it.

**Comment by aseemw** [comment]
The name of the input in the TF graph is "image:0" and not "input:0" which you are providing through input_name_shape_dict to the converter function.

**Comment by bowsplinter** [comment]
cheers, that and changing the output_feature_names from `['import/Openpose/concat_stage7:0']` to `['Openpose/concat_stage7:0']` fixed it! thanks
