### ISSUE TITLE
Converting from retrained inception v3 protobuff file throws error 

### ISSUE THREAD

**Issue by ashermancinelli** [tf-coreml/tf-coreml#200]
I have a retrained Inception V3 model which I have frozen with:
```
import tensorflow as tf
from tensorflow.python.framework.graph_util import convert_variables_to_constants as conv
from tensorflow.python.platform import gfile

saver = tf.train.import_meta_graph('path/to/ckpt.meta', clear_devices=True)
graph = tf.get_default_graph()

with tf.Session() as s:
        saver.restore(s, tf.train.latest_checkpoint('models/cnn/'))
        minimal_graph = conv(s, graph.as_graph_def(), ["output_name"])
        with tf.gfile.GFile('frozen_model.pb', 'wb') as f:
                f.write(minimal_graph.SerializeToString())
```

And now I am trying to convert the protobuff file to an mlmodel file with tfcoreml.convert:

```
import tfcoreml as converter
converter.convert(
        tf_model_path='frozen_model.pb',
        mlmodel_path='frozen_model.mlmodel',
        output_feature_names=['new_output_layer/probability'],
        image_input_names=['input:0'],
        input_name_shape_dict={'input:0':[1, 299, 299, 3]},
        image_scale=1/255.0,
        class_labels='class_labels.txt'
)
```

And this throws `tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[1] does not have value`.
Tried rolling back from tf==1.8 to tf==1.5 and removing various arguments to find problem, yet nothing will stop this error. 
Trained on dedicated machine with tf-gpu, using vanilla tf on current machine.

Full stack trace:
```
WARNING:root:Keras version 2.1.6 detected. Last version known to be fully compatible of Keras is 2.1.3 .
2018-06-08 14:02:30.472683: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX
Shapes not found for 893 tensors. Executing graph to determine shapes. 
Traceback (most recent call last):
  File "/Users/manc568/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/Users/manc568/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/Users/manc568/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[1] does not have value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "convert_to_coreml.py", line 27, in <module>
    class_labels='class_labels.txt'
  File "/Users/manc568/miniconda3/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 552, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/Users/manc568/miniconda3/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 227, in _convert_pb_to_mlmodel
    tensors_evaluated = sess.run(tensors, feed_dict=input_feed_dict)
  File "/Users/manc568/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/manc568/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/manc568/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/Users/manc568/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[1] does not have value
```
The last callback seems to be triggered by the `class_labels` param, but this throws on the last param no matter what it is. 

Help is appreciated, Thank you

**Comment by ashermancinelli** [comment]
@aseemw @slin07

**Comment by aseemw** [comment]
The converter tries to run the TF graph once before conversion. This error message is thrown while doing that. 

Can you check that you are able to load the TF frozen graph and run it with a (say) random input? 
(you can check the code in the example ipython notebooks on how to do that). This will not involve the converter at all.

**Comment by ashermancinelli** [comment]
I ran my model in the same fashion as the example notebooks:

```
import tensorflow as tf
from tensorflow.python.platform import gfile
import cv2
import numpy as np

with gfile.FastGFile('path/to/frozen/pbfile', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

x, pred = tf.import_graph_def(
        graph_def,
        name='',
        return_elements=[
            'input:0',
            'output_op'
        ]
)

pred = pred.outputs[0]

img = np.array(cv2.imread('path/to/img'))
img = np.divide(img, 255)
img = cv2.resize(img, dsize=(299, 299), interpolation=cv2.INTER_CUBIC)

init = [ tf.global_variables_initializer(), tf.local_variables_initializer() ]

with tf.Session() as sess:

    sess.run(init)

    r = sess.run(
        pred,
        feed_dict={x: [img]}
    )

```
Yet I still get the same result when I try to convert to coreml.

**Comment by aseemw** [comment]
what is the value of `pred` in the code above? Try printing it. 
 `Retval[1]` refers to the second element of `pred`. That should be a tensor which is in the graph. The Tensorflow error you are getting is because it fails to evaluate the second tensor in `pred`.

**Comment by ashermancinelli** [comment]
printing the whole op gives: 
```
name: "new_output_layer/probability"
op: "Softmax"
input: "new_output_layer/logits/BiasAdd"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
```
and printing op.outputs gives:
`[<tf.Tensor 'new_output_layer/probability:0' shape=(?, 3) dtype=float32>]`
both of which only seem to have one output. What is the second element?

**Comment by aseemw** [comment]
When you make this call: 
```
    r = sess.run(
        pred,
        feed_dict={x: [img]}
    )
```
graph is executed to find the value of "pred". It seems 'pred' is a list of two elements and its not able to get the value of the second element in that list. 

I do not know. Maybe something is wrong in the way you are saving the graph or calling incorrect tensor names. 
Try sth like this: 
`sess.run('Softmax:0', feed_dict={x:np.random.rand(1,299,299,3)})`
(See example notebooks in this repo to see more examples)

**Comment by ashermancinelli** [comment]
You're right, seems to be a problem with freezing layers for coreml and not tf-coreml itself.

**Comment by ashermancinelli** [comment]
After investigating your code, I can't seem to figure out what's going wrong, but I am confident that my model has been saved correctly. I used `tf.train.write_graph` to write the session, `python -m tensorflow.python.tools.freeze_graph` to freeze the graph, bazel to build the `tensorflow/tools/graph_transforms:transform_graph` function from source, and my naming conventions are consistent. I can run an isolated test case with: 
```
# opening file just as examples show
with gfile.FastGFile('pbdir/optimized_inception_graph.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

# testing if we can get variables/ops from graph_def
x, op = tf.import_graph_def(
        graph_def, 
        name='',
        return_elements=[
            'input:0',
            'output'
        ]   
)

print(op)

init = [ tf.global_variables_initializer(), tf.local_variables_initializer() ]

with tf.Session() as sess:

    sess.run(init)

    # Using exact same names here as in tfcoreml.convert function
    r = sess.run(
        'output:0',
        feed_dict={'input:0': np.random.rand(1, 299, 299, 3)} 
    )   

    print(r)
```
which prints the op and the result successfully:
op:
```
name: "output"
op: "Softmax"
input: "logits/BiasAdd"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
```
result:
`[[ 0.19705854  0.21740404  0.58553743]]`

I cannot seem to reproduce this error outside of tfcoreml, so I believe something is wrong in the module. I edited the _tf_coreml_converter.py to write the values of `tensor_names` and `tensors` from `tensor_names, tensors = zip(*shapes_wanted)` to file, as that may be part of where the error is coming from, but both seem to line up with my actual graph just fine. I also printed out the `input_feed_dict`, which gives `<tf.Tensor 'input:0' shape=(?, 299, 299, 3) dtype=float32>` as the key with an array of shape (?, 299, 299, 3) as it should be. I have checked that none of my other tensors expect an output, so there should only be one return value, that of the `output:0` op. Is there a way to trace `Retval` to the tensor that wants to return something? Is there something in the module that modifies the tensors to cause this?

**Comment by aseemw** [comment]
can you attach the model "optimized_inception_graph.pb"

**Comment by ashermancinelli** [comment]
https://github.com/ashermancinelli/temp.git
Warning: 80m file

**Comment by ashermancinelli** [comment]
Experimenting with the code in `_tf_coreml_converter.py`, I found that I can run the first and last nodes with 
```
sess.run(tensors[0], feed_dict=input_feed_dict)
tensors_evaluated = sess.run(tensors[-1], feed_dict=input_feed_dict)
```
and both run successfully, but running the inner tensors with: 
`sess.run(tensors[1:-1])`
gives:
`You must feed a value for placeholder tensor 'input' with dtype float and shape [?,299,299,3]`
so I run with `feed_dict`:
`sess.run(tensors[1:-1], feed_dict=input_feed_dict)`
and get the same old error:
`Retval[1] does not have value`.
This is strange because I assumed before that the `Retval[1]` was the second return value from the `session.run` which wasn't being handled, but this still happens when the real output op isn't even being ran. All the ops besides the `output` are frozen, so why then is an inner op from the inception model failing when ran in the module?

**Comment by aseemw** [comment]
This graph seems to have a similar issue to #195 (see the comments there), in which the Batchnorm op is still in training mode and has "switch" ops (which are not supported in CoreML)

**Comment by Mstronach** [comment]
Can you try again with the latest version and let us know if you are still experiencing this issue? Thanks.
