### ISSUE TITLE
Retval[108] does not have value

### ISSUE THREAD

**Issue by nam1665** [tf-coreml/tf-coreml#205]
Hi, I want to convert my .pb file to coreml. But when I run the command, it's failed and the log is:
Traceback (most recent call last):
 File "convert.py", line 5, in <module>
   input_name_shape_dict = {'input_tensor:0' : [1, 224, 224, 3]})
 File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 552, in convert
   custom_conversion_functions=custom_conversion_functions)
 File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 227, in _convert_pb_to_mlmodel
   tensors_evaluated = sess.run(tensors, feed_dict=input_feed_dict)
 File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
   run_metadata_ptr)
 File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
   feed_dict_tensor, options, run_metadata)
 File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
   run_metadata)
 File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
   raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[108] does not have value

This is my python code: 
import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'after_clustering_margin05.pb',
                     mlmodel_path = 'my_model.mlmodel',
                     output_feature_names = ['Softmax:0'],
                     input_name_shape_dict = {'input_tensor:0' : [1, 224, 224, 3]})

When using inspect tools. the input_tensor is: input_tensor:0 : (?, 224, 224, 3). So I change "?" to "1", is that correct?
Thank you so much

**Comment by aseemw** [comment]
Yes.

**Comment by pavan4** [comment]
I am facing the same issue as well. 

.pb loads properly and takes the following input and outputs:

```
input_1:0, shape: (?, 256, 256, 3),
1_conv_1x1_parts/BiasAdd:0, shape: (?, 64, 64, 16),
```

My converter is looking like this : 

```
import tfcoreml

tf_model_path= './mymodel.pb'
input_tensor_shapes = {"input_1:0":[1,256,256,3]} 
image_input_name = ['input_1:0']
coreml_model_file = './mymodel.mlmodel'
output_tensor_names = ['1_conv_1x1_parts/BiasAdd:0']

coreml_model = tfcoreml.convert(
        tf_model_path=tf_model_path,
        mlmodel_path=coreml_model_file,
        input_name_shape_dict=input_tensor_shapes,
        output_feature_names=output_tensor_names,
        image_input_names = image_input_name)
```

When I convert I get this error: 

```
Loading the TF graph...
Graph Loaded.
Collecting all the 'Const' ops from the graph, by running it....
.
.
.
InvalidArgumentError: Retval[169] does not have value
```

**Comment by pavan4** [comment]
I ran the script from [here](https://github.com/tf-coreml/tf-coreml/blob/master/utils/inspect_pb.py) and got these ops: 

--------------
OPS counts:
Placeholder : 1
PlaceholderWithDefault : 1
Range : 1
Square : 1
Log : 1
Exp : 1
Sum : 1
Equal : 1
Where : 1
Sub : 2
RealDiv : 2
ExpandDims : 2
Max : 2
Transpose : 4
Shape : 6
StridedSlice : 6
ResizeNearestNeighbor : 6
MaxPool : 8
Mul : 10
Add : 42
Merge : 96
Relu : 98
BiasAdd : 102
Conv2D : 103
FusedBatchNorm : 192
Switch : 576
Identity : 686
Const : 823

I see some ops are not supported. Is this the reason why?

**Comment by y-ich** [comment]
I encountered the same error.
I want to request some improvement of error message for debugging.

Thank you.

**Comment by danvargg** [comment]
Encountered the same issue:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[26] does not have value`
