### ISSUE TITLE
Error converting .pb to .mlmodel

### ISSUE THREAD

**Issue by astha94** [tf-coreml/tf-coreml#209]
I am trying to incorporate my trained CNN text classifier, created following this tutorial:
http://www.wildml.com/2015/12/implementing-a-cnn-for-text-classification-in-tensorflow/

I have created a model, represented using a checkpoints directory. I would like to incorporate this into my IOS app. 

I have frozen this model, and removed any dropouts from the frozen model. This has resulted in the following tensors output:
```
0 output/b_0/grad/sparsity/tags Const
1 zero_fraction_8/Const Const
2 zero_fraction_8/zero Const
3 gradients/loss/SoftmaxCrossEntropyWithLogits_grad/ExpandDims/dim Const
4 gradients/output/add_1_grad/Shape_1 Const
5 gradients/output/add_1_grad/Shape Const
6 gradients/output/add_1_grad/BroadcastGradientArgs BroadcastGradientArgs
└─── 0 ─ gradients/output/add_1_grad/Shape
└─── 1 ─ gradients/output/add_1_grad/Shape_1
7 gradients/loss/mul_grad/Shape_1 Const
8 gradients/loss/mul_grad/Shape Const
9 gradients/loss/mul_grad/BroadcastGradientArgs BroadcastGradientArgs
└─── 0 ─ gradients/loss/mul_grad/Shape
└─── 1 ─ gradients/loss/mul_grad/Shape_1
10 gradients/loss/Mean_grad/Maximum/y Const
11 gradients/loss/Mean_grad/Const_1 Const
12 gradients/loss/Mean_grad/Const Const
13 gradients/loss/Mean_grad/Shape_2 Const
14 gradients/loss/Mean_grad/Prod_1 Prod
└─── 0 ─ gradients/loss/Mean_grad/Shape_2
└─── 1 ─ gradients/loss/Mean_grad/Const_1
15 gradients/loss/Mean_grad/Maximum Maximum
└─── 0 ─ gradients/loss/Mean_grad/Prod_1
└─── 1 ─ gradients/loss/Mean_grad/Maximum/y
16 gradients/loss/Mean_grad/Reshape/shape Const
17 gradients/loss/add_grad/Shape_1 Const
18 gradients/loss/add_grad/Shape Const
19 gradients/loss/add_grad/BroadcastGradientArgs BroadcastGradientArgs
└─── 0 ─ gradients/loss/add_grad/Shape
└─── 1 ─ gradients/loss/add_grad/Shape_1
20 gradients/Const Const
21 gradients/Shape Const
22 gradients/Fill Fill
└─── 0 ─ gradients/Shape
└─── 1 ─ gradients/Const
23 gradients/loss/add_grad/Sum_1 Sum
└─── 0 ─ gradients/Fill
└─── 1 ─ gradients/loss/add_grad/BroadcastGradientArgs:1
24 gradients/loss/add_grad/Reshape_1 Reshape
└─── 0 ─ gradients/loss/add_grad/Sum_1
└─── 1 ─ gradients/loss/add_grad/Shape_1
25 gradients/loss/add_grad/Sum Sum
└─── 0 ─ gradients/Fill
└─── 1 ─ gradients/loss/add_grad/BroadcastGradientArgs
26 gradients/loss/add_grad/Reshape Reshape
└─── 0 ─ gradients/loss/add_grad/Sum
└─── 1 ─ gradients/loss/add_grad/Shape
27 gradients/loss/add_grad/tuple/group_deps NoOp
└─── 0 ─ ^gradients/loss/add_grad/Reshape
└─── 1 ─ ^gradients/loss/add_grad/Reshape_1
28 gradients/loss/add_grad/tuple/control_dependency_1 Identity
└─── 0 ─ gradients/loss/add_grad/Reshape_1
└─── 1 ─ ^gradients/loss/add_grad/tuple/group_deps
29 gradients/loss/add_grad/tuple/control_dependency Identity
└─── 0 ─ gradients/loss/add_grad/Reshape
└─── 1 ─ ^gradients/loss/add_grad/tuple/group_deps
30 gradients/loss/Mean_grad/Reshape Reshape
└─── 0 ─ gradients/loss/add_grad/tuple/control_dependency
└─── 1 ─ gradients/loss/Mean_grad/Reshape/shape
31 loss/mul/x Const
32 gradients/loss/mul_grad/mul_1 Mul
└─── 0 ─ loss/mul/x
└─── 1 ─ gradients/loss/add_grad/tuple/control_dependency_1
33 gradients/loss/mul_grad/Sum_1 Sum
└─── 0 ─ gradients/loss/mul_grad/mul_1
└─── 1 ─ gradients/loss/mul_grad/BroadcastGradientArgs:1
34 gradients/loss/mul_grad/Reshape_1 Reshape
└─── 0 ─ gradients/loss/mul_grad/Sum_1
└─── 1 ─ gradients/loss/mul_grad/Shape_1
35 loss/Slice_2/begin Const
36 loss/Sub_2/y Const
37 loss/concat_1/axis Const
38 loss/concat_1/values_0 Const
39 loss/Slice_1/size Const
40 loss/Sub_1/y Const
41 loss/Rank_2 Const
42 loss/Sub_1 Sub
└─── 0 ─ loss/Rank_2
└─── 1 ─ loss/Sub_1/y
43 loss/Slice_1/begin Pack
└─── 0 ─ loss/Sub_1
44 loss/concat/axis Const
45 loss/concat/values_0 Const
46 loss/Slice/size Const
47 loss/Sub/y Const
48 loss/Rank_1 Const
49 loss/Sub Sub
└─── 0 ─ loss/Rank_1
└─── 1 ─ loss/Sub/y
50 loss/Slice/begin Pack
└─── 0 ─ loss/Sub
51 loss/Rank Const
52 loss/Sub_2 Sub
└─── 0 ─ loss/Rank
└─── 1 ─ loss/Sub_2/y
53 loss/Slice_2/size Pack
└─── 0 ─ loss/Sub_2
54 output/b Const
55 output/b/read Identity
└─── 0 ─ output/b
56 output/L2Loss_1 L2Loss
└─── 0 ─ output/b/read
57 W Const
58 W/read Identity
└─── 0 ─ W
59 output/L2Loss L2Loss
└─── 0 ─ W/read
60 Reshape/shape Const
61 concat/axis Const
62 conv-maxpool-3/b Const
63 conv-maxpool-3/b/read Identity
└─── 0 ─ conv-maxpool-3/b
64 conv-maxpool-3/W Const
65 conv-maxpool-3/W/read Identity
└─── 0 ─ conv-maxpool-3/W
66 conv-maxpool-2/b Const
67 conv-maxpool-2/b/read Identity
└─── 0 ─ conv-maxpool-2/b
68 conv-maxpool-2/W Const
69 conv-maxpool-2/W/read Identity
└─── 0 ─ conv-maxpool-2/W
70 conv-maxpool-1/b Const
71 conv-maxpool-1/b/read Identity
└─── 0 ─ conv-maxpool-1/b
72 conv-maxpool-1/W Const
73 conv-maxpool-1/W/read Identity
└─── 0 ─ conv-maxpool-1/W
74 embedding/ExpandDims/dim Const
75 embedding/W Const
76 embedding/W/read Identity
└─── 0 ─ embedding/W
77 Const Const
78 output/add Add
└─── 0 ─ Const
└─── 1 ─ output/L2Loss
79 output/add_1 Add
└─── 0 ─ output/add
└─── 1 ─ output/L2Loss_1
80 gradients/loss/mul_grad/mul Mul
└─── 0 ─ gradients/loss/add_grad/tuple/control_dependency_1
└─── 1 ─ output/add_1
81 gradients/loss/mul_grad/Sum Sum
└─── 0 ─ gradients/loss/mul_grad/mul
└─── 1 ─ gradients/loss/mul_grad/BroadcastGradientArgs
82 gradients/loss/mul_grad/Reshape Reshape
└─── 0 ─ gradients/loss/mul_grad/Sum
└─── 1 ─ gradients/loss/mul_grad/Shape
83 gradients/loss/mul_grad/tuple/group_deps NoOp
└─── 0 ─ ^gradients/loss/mul_grad/Reshape
└─── 1 ─ ^gradients/loss/mul_grad/Reshape_1
84 gradients/loss/mul_grad/tuple/control_dependency_1 Identity
└─── 0 ─ gradients/loss/mul_grad/Reshape_1
└─── 1 ─ ^gradients/loss/mul_grad/tuple/group_deps
85 gradients/output/add_1_grad/Sum_1 Sum
└─── 0 ─ gradients/loss/mul_grad/tuple/control_dependency_1
└─── 1 ─ gradients/output/add_1_grad/BroadcastGradientArgs:1
86 gradients/output/add_1_grad/Reshape_1 Reshape
└─── 0 ─ gradients/output/add_1_grad/Sum_1
└─── 1 ─ gradients/output/add_1_grad/Shape_1
87 gradients/output/add_1_grad/Sum Sum
└─── 0 ─ gradients/loss/mul_grad/tuple/control_dependency_1
└─── 1 ─ gradients/output/add_1_grad/BroadcastGradientArgs
88 gradients/output/add_1_grad/Reshape Reshape
└─── 0 ─ gradients/output/add_1_grad/Sum
└─── 1 ─ gradients/output/add_1_grad/Shape
89 gradients/output/add_1_grad/tuple/group_deps NoOp
└─── 0 ─ ^gradients/output/add_1_grad/Reshape
└─── 1 ─ ^gradients/output/add_1_grad/Reshape_1
90 gradients/output/add_1_grad/tuple/control_dependency_1 Identity
└─── 0 ─ gradients/output/add_1_grad/Reshape_1
└─── 1 ─ ^gradients/output/add_1_grad/tuple/group_deps
91 gradients/output/L2Loss_1_grad/mul Mul
└─── 0 ─ output/b/read
└─── 1 ─ gradients/output/add_1_grad/tuple/control_dependency_1
92 input_y Placeholder
93 loss/Shape_2 Shape
└─── 0 ─ input_y
94 loss/Slice_1 Slice
└─── 0 ─ loss/Shape_2
└─── 1 ─ loss/Slice_1/begin
└─── 2 ─ loss/Slice_1/size
95 loss/concat_1 ConcatV2
└─── 0 ─ loss/concat_1/values_0
└─── 1 ─ loss/Slice_1
└─── 2 ─ loss/concat_1/axis
96 loss/Reshape_1 Reshape
└─── 0 ─ input_y
└─── 1 ─ loss/concat_1
97 input_x Placeholder
98 embedding/embedding_lookup Gather
└─── 0 ─ embedding/W/read
└─── 1 ─ input_x
99 embedding/ExpandDims ExpandDims
└─── 0 ─ embedding/embedding_lookup
└─── 1 ─ embedding/ExpandDims/dim
100 conv-maxpool-3/conv Conv2D
└─── 0 ─ embedding/ExpandDims
└─── 1 ─ conv-maxpool-3/W/read
101 conv-maxpool-3/BiasAdd BiasAdd
└─── 0 ─ conv-maxpool-3/conv
└─── 1 ─ conv-maxpool-3/b/read
102 conv-maxpool-3/relu Relu
└─── 0 ─ conv-maxpool-3/BiasAdd
103 conv-maxpool-3/pool MaxPool
└─── 0 ─ conv-maxpool-3/relu
104 conv-maxpool-2/conv Conv2D
└─── 0 ─ embedding/ExpandDims
└─── 1 ─ conv-maxpool-2/W/read
105 conv-maxpool-2/BiasAdd BiasAdd
└─── 0 ─ conv-maxpool-2/conv
└─── 1 ─ conv-maxpool-2/b/read
106 conv-maxpool-2/relu Relu
└─── 0 ─ conv-maxpool-2/BiasAdd
107 conv-maxpool-2/pool MaxPool
└─── 0 ─ conv-maxpool-2/relu
108 conv-maxpool-1/conv Conv2D
└─── 0 ─ embedding/ExpandDims
└─── 1 ─ conv-maxpool-1/W/read
109 conv-maxpool-1/BiasAdd BiasAdd
└─── 0 ─ conv-maxpool-1/conv
└─── 1 ─ conv-maxpool-1/b/read
110 conv-maxpool-1/relu Relu
└─── 0 ─ conv-maxpool-1/BiasAdd
111 conv-maxpool-1/pool MaxPool
└─── 0 ─ conv-maxpool-1/relu
112 concat ConcatV2
└─── 0 ─ conv-maxpool-1/pool
└─── 1 ─ conv-maxpool-2/pool
└─── 2 ─ conv-maxpool-3/pool
└─── 3 ─ concat/axis
113 Reshape Reshape
└─── 0 ─ concat
└─── 1 ─ Reshape/shape
114 output/scores/MatMul MatMul
└─── 0 ─ Reshape
└─── 1 ─ W/read
115 output/scores BiasAdd
└─── 0 ─ output/scores/MatMul
└─── 1 ─ output/b/read
116 gradients/loss/Reshape_grad/Shape Shape
└─── 0 ─ output/scores
117 loss/Shape_1 Shape
└─── 0 ─ output/scores
118 loss/Slice Slice
└─── 0 ─ loss/Shape_1
└─── 1 ─ loss/Slice/begin
└─── 2 ─ loss/Slice/size
119 loss/concat ConcatV2
└─── 0 ─ loss/concat/values_0
└─── 1 ─ loss/Slice
└─── 2 ─ loss/concat/axis
120 loss/Reshape Reshape
└─── 0 ─ output/scores
└─── 1 ─ loss/concat
121 loss/SoftmaxCrossEntropyWithLogits SoftmaxCrossEntropyWithLogits
└─── 0 ─ loss/Reshape
└─── 1 ─ loss/Reshape_1
122 gradients/loss/Reshape_2_grad/Shape Shape
└─── 0 ─ loss/SoftmaxCrossEntropyWithLogits
123 loss/Shape Shape
└─── 0 ─ output/scores
124 loss/Slice_2 Slice
└─── 0 ─ loss/Shape
└─── 1 ─ loss/Slice_2/begin
└─── 2 ─ loss/Slice_2/size
125 loss/Reshape_2 Reshape
└─── 0 ─ loss/SoftmaxCrossEntropyWithLogits
└─── 1 ─ loss/Slice_2
126 gradients/loss/Mean_grad/Shape_1 Shape
└─── 0 ─ loss/Reshape_2
127 gradients/loss/Mean_grad/Prod Prod
└─── 0 ─ gradients/loss/Mean_grad/Shape_1
└─── 1 ─ gradients/loss/Mean_grad/Const
128 gradients/loss/Mean_grad/floordiv FloorDiv
└─── 0 ─ gradients/loss/Mean_grad/Prod
└─── 1 ─ gradients/loss/Mean_grad/Maximum
129 gradients/loss/Mean_grad/Cast Cast
└─── 0 ─ gradients/loss/Mean_grad/floordiv
130 gradients/loss/Mean_grad/Shape Shape
└─── 0 ─ loss/Reshape_2
131 gradients/loss/Mean_grad/Tile Tile
└─── 0 ─ gradients/loss/Mean_grad/Reshape
└─── 1 ─ gradients/loss/Mean_grad/Shape
132 gradients/loss/Mean_grad/truediv RealDiv
└─── 0 ─ gradients/loss/Mean_grad/Tile
└─── 1 ─ gradients/loss/Mean_grad/Cast
133 gradients/loss/Reshape_2_grad/Reshape Reshape
└─── 0 ─ gradients/loss/Mean_grad/truediv
└─── 1 ─ gradients/loss/Reshape_2_grad/Shape
134 gradients/loss/SoftmaxCrossEntropyWithLogits_grad/ExpandDims ExpandDims
└─── 0 ─ gradients/loss/Reshape_2_grad/Reshape
└─── 1 ─ gradients/loss/SoftmaxCrossEntropyWithLogits_grad/ExpandDims/dim
135 gradients/loss/SoftmaxCrossEntropyWithLogits_grad/mul Mul
└─── 0 ─ gradients/loss/SoftmaxCrossEntropyWithLogits_grad/ExpandDims
└─── 1 ─ loss/SoftmaxCrossEntropyWithLogits:1
136 gradients/loss/Reshape_grad/Reshape Reshape
└─── 0 ─ gradients/loss/SoftmaxCrossEntropyWithLogits_grad/mul
└─── 1 ─ gradients/loss/Reshape_grad/Shape
137 gradients/output/scores_grad/BiasAddGrad BiasAddGrad
└─── 0 ─ gradients/loss/Reshape_grad/Reshape
138 gradients/output/scores_grad/tuple/group_deps NoOp
└─── 0 ─ ^gradients/loss/Reshape_grad/Reshape
└─── 1 ─ ^gradients/output/scores_grad/BiasAddGrad
139 gradients/output/scores_grad/tuple/control_dependency_1 Identity
└─── 0 ─ gradients/output/scores_grad/BiasAddGrad
└─── 1 ─ ^gradients/output/scores_grad/tuple/group_deps
140 gradients/AddN AddN
└─── 0 ─ gradients/output/L2Loss_1_grad/mul
└─── 1 ─ gradients/output/scores_grad/tuple/control_dependency_1
141 zero_fraction_8/Equal Equal
└─── 0 ─ gradients/AddN
└─── 1 ─ zero_fraction_8/zero
142 zero_fraction_8/Cast Cast
└─── 0 ─ zero_fraction_8/Equal
143 zero_fraction_8/Mean Mean
└─── 0 ─ zero_fraction_8/Cast
└─── 1 ─ zero_fraction_8/Const
144 output/b_0/grad/sparsity ScalarSummary
└─── 0 ─ output/b_0/grad/sparsity/tags
└─── 1 ─ zero_fraction_8/Mean
```
When I try to run the following to convert the frozen graph to tfcoreml:
```
frozen_model_file = os.path.abspath("frozen_model_without_dropout.pb")
input_tensor_shapes = {"input_y:0" :[1, 2], "input_x:0" : [1,156]}
# Output CoreML model path
coreml_model_file = './model.mlmodel'
output_tensor_names = ['output/b_0/grad/sparsity:0']
def convert():
    # Read the pb model
    with tf.gfile.GFile(frozen_model_file, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())

    # Then, we import the graph_def into a new Graph
    tf.import_graph_def(graph_def, name="")

    # Convert
    tfcoreml.convert(
        tf_model_path=frozen_model_file,
        mlmodel_path=coreml_model_file,
        input_name_shape_dict=input_tensor_shapes,
        output_feature_names=output_tensor_names

        )

convert()
```
I get the following issue:

```
Traceback (most recent call last):
  File "convert_pb_tfcoreml.py", line 80, in <module>
    convert()
  File "convert_pb_tfcoreml.py", line 76, in convert
    output_feature_names=output_tensor_names
  File "/home/ubuntu/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 552, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/home/ubuntu/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 262, in _convert_pb_to_mlmodel
    unused_ops, effectively_constant_ops = _find_unused_ops(OPS, sess, output_feature_names, input_feed_dict, input_feed_dict2) # return type: List[str], List[str]
  File "/home/ubuntu/tf-coreml/tfcoreml/_tf_graph_transform.py", line 99, in _find_unused_ops
    out1 = tensors_evaluated1[idx].flatten().astype(np.float32)
AttributeError: 'str' object has no attribute 'flatten'
```

I think the issue is linked to the shape of my tensors, but I am not sure exactly and how to fix it. Also if there is a more intuitive way to incorporate a trained CNN text categorisation tensorflow model into an IOS app then please let me know.

**Comment by aseemw** [comment]
Hi can you check, before even proceeding with the conversion, that the you are able to load the Tensorflow's frozen graph and run it? The example Jupiter notebooks has code to how to do that. 
I suspect there is some issue with the frozen graph.

**Comment by pratik18v** [comment]
@aseemw Is embedding lookup operation supported? If not can you give some pointers on how to implement it using custom layers?

Thank you

**Comment by bhushan23** [comment]
@pratik18v here is an example of custom layer in tensorflow https://github.com/apple/coremltools/blob/master/coremltools/converters/tensorflow/test/test_custom_layer.py 

closing this issue. Please feel free to re-open if you need more help
