### ISSUE TITLE
AssertionError: Concat axis case not handled

### ISSUE THREAD

**Issue by mrgloom** [tf-coreml/tf-coreml#240]
My model contain concat layer `x = tf.concat([x, x_deltas], -1)` which produce error `AssertionError: Concat axis case not handled`.

```
529/532: Analysing op name: concat ( type:  ConcatV2 )
Traceback (most recent call last):
  File "graph_converter_utils/convert_to_coreml_eyes_ext.py", line 34, in <module>
    is_bgr=True)
  File "/Users/myuser/anaconda3/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 552, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/Users/myuser/anaconda3/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 315, in _convert_pb_to_mlmodel
    convert_ops_to_layers(context)
  File "/Users/myuser/anaconda3/lib/python3.6/site-packages/tfcoreml/_ops_to_layers.py", line 174, in convert_ops_to_layers
    translator(op, context)
  File "/Users/myuser/anaconda3/lib/python3.6/site-packages/tfcoreml/_layers.py", line 113, in concat
    ss_layers._add_concat(op, context)
  File "/Users/myuser/anaconda3/lib/python3.6/site-packages/tfcoreml/_shape_sensitive_layers.py", line 138, in _add_concat
    assert False, 'Concat axis case not handled'
AssertionError: Concat axis case not handled
```

**Comment by mrgloom** [comment]
Seems using `x = tf.concat([x, x_deltas], axis=1)` is solved the problem.

**Comment by feifeiwei** [comment]
I have meet the same error, could you please give a help?
```
1676/1998: Analysing op name: concat_1 ( type:  ConcatV2 )
Traceback (most recent call last):
  File "pb2coreml.py", line 22, in <module>
    minimum_ios_deployment_target='12')
  File "/Users/feifeiwei/anaconda3/envs/py36/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 718, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/Users/feifeiwei/anaconda3/envs/py36/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 411, in _convert_pb_to_mlmodel
    convert_ops_to_layers(context)
  File "/Users/feifeiwei/anaconda3/envs/py36/lib/python3.6/site-packages/tfcoreml/_ops_to_layers.py", line 186, in convert_ops_to_layers
    translator(op, context)
  File "/Users/feifeiwei/anaconda3/envs/py36/lib/python3.6/site-packages/tfcoreml/_layers.py", line 119, in concat
    ss_layers._add_concat(op, context)
  File "/Users/feifeiwei/anaconda3/envs/py36/lib/python3.6/site-packages/tfcoreml/_shape_sensitive_layers.py", line 138, in _add_concat
    assert False, ('Concat axis case not handled. output shape = {}, axis = {}'.format(str(output_shape), axis))
AssertionError: Concat axis case not handled. output shape = [5733, 8], axis = 0
```
