### ISSUE TITLE
ModuleNotFoundError: No module named '172'

### ISSUE THREAD

**Issue by wuliwong** [tf-coreml/tf-coreml#246]
I'm trying to run celery on an ec2 instance using `virtualenv`. I'm not sure exactly what information would be most helpful to debug. I have included the package versions and error log. 

I receive the error when I run:
`celery -A mysite worker -l info` in my project root directory. `mysite` is the correct name of the app folder.

Here are the versions I'm running
```
pip list | grep "kombu\|celery"
celery                4.2.1
django-celery-beat    1.1.1
django-celery-results 1.0.1
kombu                 4.2.1
```

```
[2018-10-03 13:19:27,963: CRITICAL/MainProcess] Unrecoverable error: ModuleNotFoundError("No module named '172'",)
Traceback (most recent call last):
  File "/home/ubuntu/python-api-env/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/python-api-env/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/home/ubuntu/python-api-env/lib/python3.6/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/home/ubuntu/python-api-env/lib/python3.6/site-packages/celery/apps/worker.py", line 139, in on_start
    self.emit_banner()
  File "/home/ubuntu/python-api-env/lib/python3.6/site-packages/celery/apps/worker.py", line 154, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/home/ubuntu/python-api-env/lib/python3.6/site-packages/celery/apps/worker.py", line 217, in startup_info
    results=self.app.backend.as_uri(),
  File "/home/ubuntu/python-api-env/lib/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/ubuntu/python-api-env/lib/python3.6/site-packages/celery/app/base.py", line 1196, in backend
    return self._get_backend()
  File "/home/ubuntu/python-api-env/lib/python3.6/site-packages/celery/app/base.py", line 914, in _get_backend
    self.loader)
  File "/home/ubuntu/python-api-env/lib/python3.6/site-packages/celery/app/backends.py", line 70, in by_url
    return by_name(backend, loader), url
  File "/home/ubuntu/python-api-env/lib/python3.6/site-packages/celery/app/backends.py", line 50, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/home/ubuntu/python-api-env/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/ubuntu/python-api-env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named '172'
```

**Comment by wuliwong** [comment]
I just didn't have the environment variables setup correctly. I would assume we should just close this unless we would consider this an issue with the error messaging.

**Comment by wuliwong** [comment]
woa, I have no idea how I wound up posting this here. Sorry about that.

**Comment by Rfank2021** [comment]
I met a similar problem in ratelimit package, it's because ip address is treated as callable.
