### ISSUE TITLE
AssertionError: input_1:0 is a placeholder with incomplete shape

### ISSUE THREAD

**Issue by Spectra456** [tf-coreml/tf-coreml#251]
> 
```
import tfcoreml

# Supply a dictionary of input tensors' name and shape (with batch axis)
input_tensor_shapes = {"input:0": [4, 256, 256, 3]}  # batch size is 1
# TF graph definition
tf_model_path = 'tfmodel.pb'
# Output CoreML model path
coreml_model_file = 'templft.mlmodel'
# The TF model's ouput tensor name
output_tensor_names = ['final_result:0']

# Call the converter. This may take a while
coreml_model = tfcoreml.convert(
    tf_model_path=tf_model_path,
    mlmodel_path=coreml_model_file,
    input_name_shape_dict=input_tensor_shapes,
    output_feature_names=output_tensor_names,
    image_input_names=['input:0'],
    red_bias=-1,
    green_bias=-1,
    blue_bias=-1,
    image_scale=1.)
```

Error
>`WARNING:root:TensorFlow version 1.11.0 detected. Last version known to be fully compatible is 1.5.0 .
2018-10-21 20:53:10.433528: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/spectra/projectDNN/mobile-unet/tf2ml.py", line 23, in <module>
    image_scale=1.)
  File "/home/spectra/.virtualenvs/virtual-py3/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 552, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/home/spectra/.virtualenvs/virtual-py3/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 198, in _convert_pb_to_mlmodel
    "%s is a placeholder with incomplete shape %s" %(input_name, str(shape)))
AssertionError: input_1:0 is a placeholder with incomplete shape (?, 256, 256, 3)`

### How i can fix this?

**Comment by aseemw** [comment]
Can you install from [source](https://github.com/tf-coreml/tf-coreml#install-from-source) (tip of master) and try converting again?

**Comment by Spectra456** [comment]
> Can you install from [source](https://github.com/tf-coreml/tf-coreml#install-from-source) (tip of master) and try converting again?

Thank you very much. Now i have another problem:
`ValueError: output name: Sigmoid:0, was provided, but the Tensorflow graph does not contain a tensor with this name.
`
**List of my tensors:**
```
import/input_1
import/conv2d_1/kernel
import/conv2d_1/kernel/read
import/conv2d_1/bias
import/conv2d_1/bias/read
import/conv2d_1/convolution
import/conv2d_1/BiasAdd
import/batch_normalization_1/gamma
import/batch_normalization_1/gamma/read
import/batch_normalization_1/beta
import/batch_normalization_1/beta/read
import/batch_normalization_1/moving_mean
import/batch_normalization_1/moving_mean/read
import/batch_normalization_1/moving_variance
import/batch_normalization_1/moving_variance/read
import/batch_normalization_1/batchnorm_1/add/y
import/batch_normalization_1/batchnorm_1/add
import/batch_normalization_1/batchnorm_1/Rsqrt
import/batch_normalization_1/batchnorm_1/mul
import/batch_normalization_1/batchnorm_1/mul_1
import/batch_normalization_1/batchnorm_1/mul_2
import/batch_normalization_1/batchnorm_1/sub
import/batch_normalization_1/batchnorm_1/add_1
import/activation_1/Relu
import/conv2d_2/kernel
import/conv2d_2/kernel/read
import/conv2d_2/bias
import/conv2d_2/bias/read
import/conv2d_2/convolution
import/conv2d_2/BiasAdd
import/batch_normalization_2/gamma
import/batch_normalization_2/gamma/read
import/batch_normalization_2/beta
import/batch_normalization_2/beta/read
import/batch_normalization_2/moving_mean
import/batch_normalization_2/moving_mean/read
import/batch_normalization_2/moving_variance
import/batch_normalization_2/moving_variance/read
import/batch_normalization_2/batchnorm_1/add/y
import/batch_normalization_2/batchnorm_1/add
import/batch_normalization_2/batchnorm_1/Rsqrt
import/batch_normalization_2/batchnorm_1/mul
import/batch_normalization_2/batchnorm_1/mul_1
import/batch_normalization_2/batchnorm_1/mul_2
import/batch_normalization_2/batchnorm_1/sub
import/batch_normalization_2/batchnorm_1/add_1
import/activation_2/Relu
import/max_pooling2d_1/MaxPool
import/conv2d_3/kernel
import/conv2d_3/kernel/read
import/conv2d_3/bias
import/conv2d_3/bias/read
import/conv2d_3/convolution
import/conv2d_3/BiasAdd
import/batch_normalization_3/gamma
import/batch_normalization_3/gamma/read
import/batch_normalization_3/beta
import/batch_normalization_3/beta/read
import/batch_normalization_3/moving_mean
import/batch_normalization_3/moving_mean/read
import/batch_normalization_3/moving_variance
import/batch_normalization_3/moving_variance/read
import/batch_normalization_3/batchnorm_1/add/y
import/batch_normalization_3/batchnorm_1/add
import/batch_normalization_3/batchnorm_1/Rsqrt
import/batch_normalization_3/batchnorm_1/mul
import/batch_normalization_3/batchnorm_1/mul_1
import/batch_normalization_3/batchnorm_1/mul_2
import/batch_normalization_3/batchnorm_1/sub
import/batch_normalization_3/batchnorm_1/add_1
import/activation_3/Relu
import/conv2d_4/kernel
import/conv2d_4/kernel/read
import/conv2d_4/bias
import/conv2d_4/bias/read
import/conv2d_4/convolution
import/conv2d_4/BiasAdd
import/batch_normalization_4/gamma
import/batch_normalization_4/gamma/read
import/batch_normalization_4/beta
import/batch_normalization_4/beta/read
import/batch_normalization_4/moving_mean
import/batch_normalization_4/moving_mean/read
import/batch_normalization_4/moving_variance
import/batch_normalization_4/moving_variance/read
import/batch_normalization_4/batchnorm_1/add/y
import/batch_normalization_4/batchnorm_1/add
import/batch_normalization_4/batchnorm_1/Rsqrt
import/batch_normalization_4/batchnorm_1/mul
import/batch_normalization_4/batchnorm_1/mul_1
import/batch_normalization_4/batchnorm_1/mul_2
import/batch_normalization_4/batchnorm_1/sub
import/batch_normalization_4/batchnorm_1/add_1
import/activation_4/Relu
import/max_pooling2d_2/MaxPool
import/conv2d_5/kernel
import/conv2d_5/kernel/read
import/conv2d_5/bias
import/conv2d_5/bias/read
import/conv2d_5/convolution
import/conv2d_5/BiasAdd
import/batch_normalization_5/gamma
import/batch_normalization_5/gamma/read
import/batch_normalization_5/beta
import/batch_normalization_5/beta/read
import/batch_normalization_5/moving_mean
import/batch_normalization_5/moving_mean/read
import/batch_normalization_5/moving_variance
import/batch_normalization_5/moving_variance/read
import/batch_normalization_5/batchnorm_1/add/y
import/batch_normalization_5/batchnorm_1/add
import/batch_normalization_5/batchnorm_1/Rsqrt
import/batch_normalization_5/batchnorm_1/mul
import/batch_normalization_5/batchnorm_1/mul_1
import/batch_normalization_5/batchnorm_1/mul_2
import/batch_normalization_5/batchnorm_1/sub
import/batch_normalization_5/batchnorm_1/add_1
import/activation_5/Relu
import/conv2d_6/kernel
import/conv2d_6/kernel/read
import/conv2d_6/bias
import/conv2d_6/bias/read
import/conv2d_6/convolution
import/conv2d_6/BiasAdd
import/batch_normalization_6/gamma
import/batch_normalization_6/gamma/read
import/batch_normalization_6/beta
import/batch_normalization_6/beta/read
import/batch_normalization_6/moving_mean
import/batch_normalization_6/moving_mean/read
import/batch_normalization_6/moving_variance
import/batch_normalization_6/moving_variance/read
import/batch_normalization_6/batchnorm_1/add/y
import/batch_normalization_6/batchnorm_1/add
import/batch_normalization_6/batchnorm_1/Rsqrt
import/batch_normalization_6/batchnorm_1/mul
import/batch_normalization_6/batchnorm_1/mul_1
import/batch_normalization_6/batchnorm_1/mul_2
import/batch_normalization_6/batchnorm_1/sub
import/batch_normalization_6/batchnorm_1/add_1
import/activation_6/Relu
import/max_pooling2d_3/MaxPool
import/conv2d_7/kernel
import/conv2d_7/kernel/read
import/conv2d_7/bias
import/conv2d_7/bias/read
import/conv2d_7/convolution
import/conv2d_7/BiasAdd
import/batch_normalization_7/gamma
import/batch_normalization_7/gamma/read
import/batch_normalization_7/beta
import/batch_normalization_7/beta/read
import/batch_normalization_7/moving_mean
import/batch_normalization_7/moving_mean/read
import/batch_normalization_7/moving_variance
import/batch_normalization_7/moving_variance/read
import/batch_normalization_7/batchnorm_1/add/y
import/batch_normalization_7/batchnorm_1/add
import/batch_normalization_7/batchnorm_1/Rsqrt
import/batch_normalization_7/batchnorm_1/mul
import/batch_normalization_7/batchnorm_1/mul_1
import/batch_normalization_7/batchnorm_1/mul_2
import/batch_normalization_7/batchnorm_1/sub
import/batch_normalization_7/batchnorm_1/add_1
import/activation_7/Relu
import/conv2d_8/kernel
import/conv2d_8/kernel/read
import/conv2d_8/bias
import/conv2d_8/bias/read
import/conv2d_8/convolution
import/conv2d_8/BiasAdd
import/batch_normalization_8/gamma
import/batch_normalization_8/gamma/read
import/batch_normalization_8/beta
import/batch_normalization_8/beta/read
import/batch_normalization_8/moving_mean
import/batch_normalization_8/moving_mean/read
import/batch_normalization_8/moving_variance
import/batch_normalization_8/moving_variance/read
import/batch_normalization_8/batchnorm_1/add/y
import/batch_normalization_8/batchnorm_1/add
import/batch_normalization_8/batchnorm_1/Rsqrt
import/batch_normalization_8/batchnorm_1/mul
import/batch_normalization_8/batchnorm_1/mul_1
import/batch_normalization_8/batchnorm_1/mul_2
import/batch_normalization_8/batchnorm_1/sub
import/batch_normalization_8/batchnorm_1/add_1
import/activation_8/Relu
import/max_pooling2d_4/MaxPool
import/conv2d_9/kernel
import/conv2d_9/kernel/read
import/conv2d_9/bias
import/conv2d_9/bias/read
import/conv2d_9/convolution
import/conv2d_9/BiasAdd
import/batch_normalization_9/gamma
import/batch_normalization_9/gamma/read
import/batch_normalization_9/beta
import/batch_normalization_9/beta/read
import/batch_normalization_9/moving_mean
import/batch_normalization_9/moving_mean/read
import/batch_normalization_9/moving_variance
import/batch_normalization_9/moving_variance/read
import/batch_normalization_9/batchnorm_1/add/y
import/batch_normalization_9/batchnorm_1/add
import/batch_normalization_9/batchnorm_1/Rsqrt
import/batch_normalization_9/batchnorm_1/mul
import/batch_normalization_9/batchnorm_1/mul_1
import/batch_normalization_9/batchnorm_1/mul_2
import/batch_normalization_9/batchnorm_1/sub
import/batch_normalization_9/batchnorm_1/add_1
import/activation_9/Relu
import/conv2d_10/kernel
import/conv2d_10/kernel/read
import/conv2d_10/bias
import/conv2d_10/bias/read
import/conv2d_10/convolution
import/conv2d_10/BiasAdd
import/batch_normalization_10/gamma
import/batch_normalization_10/gamma/read
import/batch_normalization_10/beta
import/batch_normalization_10/beta/read
import/batch_normalization_10/moving_mean
import/batch_normalization_10/moving_mean/read
import/batch_normalization_10/moving_variance
import/batch_normalization_10/moving_variance/read
import/batch_normalization_10/batchnorm_1/add/y
import/batch_normalization_10/batchnorm_1/add
import/batch_normalization_10/batchnorm_1/Rsqrt
import/batch_normalization_10/batchnorm_1/mul
import/batch_normalization_10/batchnorm_1/mul_1
import/batch_normalization_10/batchnorm_1/mul_2
import/batch_normalization_10/batchnorm_1/sub
import/batch_normalization_10/batchnorm_1/add_1
import/activation_10/Relu
import/max_pooling2d_5/MaxPool
import/conv2d_11/kernel
import/conv2d_11/kernel/read
import/conv2d_11/bias
import/conv2d_11/bias/read
import/conv2d_11/convolution
import/conv2d_11/BiasAdd
import/batch_normalization_11/gamma
import/batch_normalization_11/gamma/read
import/batch_normalization_11/beta
import/batch_normalization_11/beta/read
import/batch_normalization_11/moving_mean
import/batch_normalization_11/moving_mean/read
import/batch_normalization_11/moving_variance
import/batch_normalization_11/moving_variance/read
import/batch_normalization_11/batchnorm_1/add/y
import/batch_normalization_11/batchnorm_1/add
import/batch_normalization_11/batchnorm_1/Rsqrt
import/batch_normalization_11/batchnorm_1/mul
import/batch_normalization_11/batchnorm_1/mul_1
import/batch_normalization_11/batchnorm_1/mul_2
import/batch_normalization_11/batchnorm_1/sub
import/batch_normalization_11/batchnorm_1/add_1
import/activation_11/Relu
import/conv2d_12/kernel
import/conv2d_12/kernel/read
import/conv2d_12/bias
import/conv2d_12/bias/read
import/conv2d_12/convolution
import/conv2d_12/BiasAdd
import/batch_normalization_12/gamma
import/batch_normalization_12/gamma/read
import/batch_normalization_12/beta
import/batch_normalization_12/beta/read
import/batch_normalization_12/moving_mean
import/batch_normalization_12/moving_mean/read
import/batch_normalization_12/moving_variance
import/batch_normalization_12/moving_variance/read
import/batch_normalization_12/batchnorm_1/add/y
import/batch_normalization_12/batchnorm_1/add
import/batch_normalization_12/batchnorm_1/Rsqrt
import/batch_normalization_12/batchnorm_1/mul
import/batch_normalization_12/batchnorm_1/mul_1
import/batch_normalization_12/batchnorm_1/mul_2
import/batch_normalization_12/batchnorm_1/sub
import/batch_normalization_12/batchnorm_1/add_1
import/activation_12/Relu
import/up_sampling2d_1/Shape
import/up_sampling2d_1/strided_slice/stack
import/up_sampling2d_1/strided_slice/stack_1
import/up_sampling2d_1/strided_slice/stack_2
import/up_sampling2d_1/strided_slice
import/up_sampling2d_1/Const
import/up_sampling2d_1/mul
import/up_sampling2d_1/ResizeNearestNeighbor
import/concatenate_1/concat/axis
import/concatenate_1/concat
import/conv2d_13/kernel
import/conv2d_13/kernel/read
import/conv2d_13/bias
import/conv2d_13/bias/read
import/conv2d_13/convolution
import/conv2d_13/BiasAdd
import/batch_normalization_13/gamma
import/batch_normalization_13/gamma/read
import/batch_normalization_13/beta
import/batch_normalization_13/beta/read
import/batch_normalization_13/moving_mean
import/batch_normalization_13/moving_mean/read
import/batch_normalization_13/moving_variance
import/batch_normalization_13/moving_variance/read
import/batch_normalization_13/batchnorm_1/add/y
import/batch_normalization_13/batchnorm_1/add
import/batch_normalization_13/batchnorm_1/Rsqrt
import/batch_normalization_13/batchnorm_1/mul
import/batch_normalization_13/batchnorm_1/mul_1
import/batch_normalization_13/batchnorm_1/mul_2
import/batch_normalization_13/batchnorm_1/sub
import/batch_normalization_13/batchnorm_1/add_1
import/activation_13/Relu
import/conv2d_14/kernel
import/conv2d_14/kernel/read
import/conv2d_14/bias
import/conv2d_14/bias/read
import/conv2d_14/convolution
import/conv2d_14/BiasAdd
import/batch_normalization_14/gamma
import/batch_normalization_14/gamma/read
import/batch_normalization_14/beta
import/batch_normalization_14/beta/read
import/batch_normalization_14/moving_mean
import/batch_normalization_14/moving_mean/read
import/batch_normalization_14/moving_variance
import/batch_normalization_14/moving_variance/read
import/batch_normalization_14/batchnorm_1/add/y
import/batch_normalization_14/batchnorm_1/add
import/batch_normalization_14/batchnorm_1/Rsqrt
import/batch_normalization_14/batchnorm_1/mul
import/batch_normalization_14/batchnorm_1/mul_1
import/batch_normalization_14/batchnorm_1/mul_2
import/batch_normalization_14/batchnorm_1/sub
import/batch_normalization_14/batchnorm_1/add_1
import/activation_14/Relu
import/conv2d_15/kernel
import/conv2d_15/kernel/read
import/conv2d_15/bias
import/conv2d_15/bias/read
import/conv2d_15/convolution
import/conv2d_15/BiasAdd
import/batch_normalization_15/gamma
import/batch_normalization_15/gamma/read
import/batch_normalization_15/beta
import/batch_normalization_15/beta/read
import/batch_normalization_15/moving_mean
import/batch_normalization_15/moving_mean/read
import/batch_normalization_15/moving_variance
import/batch_normalization_15/moving_variance/read
import/batch_normalization_15/batchnorm_1/add/y
import/batch_normalization_15/batchnorm_1/add
import/batch_normalization_15/batchnorm_1/Rsqrt
import/batch_normalization_15/batchnorm_1/mul
import/batch_normalization_15/batchnorm_1/mul_1
import/batch_normalization_15/batchnorm_1/mul_2
import/batch_normalization_15/batchnorm_1/sub
import/batch_normalization_15/batchnorm_1/add_1
import/activation_15/Relu
import/up_sampling2d_2/Shape
import/up_sampling2d_2/strided_slice/stack
import/up_sampling2d_2/strided_slice/stack_1
import/up_sampling2d_2/strided_slice/stack_2
import/up_sampling2d_2/strided_slice
import/up_sampling2d_2/Const
import/up_sampling2d_2/mul
import/up_sampling2d_2/ResizeNearestNeighbor
import/concatenate_2/concat/axis
import/concatenate_2/concat
import/conv2d_16/kernel
import/conv2d_16/kernel/read
import/conv2d_16/bias
import/conv2d_16/bias/read
import/conv2d_16/convolution
import/conv2d_16/BiasAdd
import/batch_normalization_16/gamma
import/batch_normalization_16/gamma/read
import/batch_normalization_16/beta
import/batch_normalization_16/beta/read
import/batch_normalization_16/moving_mean
import/batch_normalization_16/moving_mean/read
import/batch_normalization_16/moving_variance
import/batch_normalization_16/moving_variance/read
import/batch_normalization_16/batchnorm_1/add/y
import/batch_normalization_16/batchnorm_1/add
import/batch_normalization_16/batchnorm_1/Rsqrt
import/batch_normalization_16/batchnorm_1/mul
import/batch_normalization_16/batchnorm_1/mul_1
import/batch_normalization_16/batchnorm_1/mul_2
import/batch_normalization_16/batchnorm_1/sub
import/batch_normalization_16/batchnorm_1/add_1
import/activation_16/Relu
import/conv2d_17/kernel
import/conv2d_17/kernel/read
import/conv2d_17/bias
import/conv2d_17/bias/read
import/conv2d_17/convolution
import/conv2d_17/BiasAdd
import/batch_normalization_17/gamma
import/batch_normalization_17/gamma/read
import/batch_normalization_17/beta
import/batch_normalization_17/beta/read
import/batch_normalization_17/moving_mean
import/batch_normalization_17/moving_mean/read
import/batch_normalization_17/moving_variance
import/batch_normalization_17/moving_variance/read
import/batch_normalization_17/batchnorm_1/add/y
import/batch_normalization_17/batchnorm_1/add
import/batch_normalization_17/batchnorm_1/Rsqrt
import/batch_normalization_17/batchnorm_1/mul
import/batch_normalization_17/batchnorm_1/mul_1
import/batch_normalization_17/batchnorm_1/mul_2
import/batch_normalization_17/batchnorm_1/sub
import/batch_normalization_17/batchnorm_1/add_1
import/activation_17/Relu
import/conv2d_18/kernel
import/conv2d_18/kernel/read
import/conv2d_18/bias
import/conv2d_18/bias/read
import/conv2d_18/convolution
import/conv2d_18/BiasAdd
import/batch_normalization_18/gamma
import/batch_normalization_18/gamma/read
import/batch_normalization_18/beta
import/batch_normalization_18/beta/read
import/batch_normalization_18/moving_mean
import/batch_normalization_18/moving_mean/read
import/batch_normalization_18/moving_variance
import/batch_normalization_18/moving_variance/read
import/batch_normalization_18/batchnorm_1/add/y
import/batch_normalization_18/batchnorm_1/add
import/batch_normalization_18/batchnorm_1/Rsqrt
import/batch_normalization_18/batchnorm_1/mul
import/batch_normalization_18/batchnorm_1/mul_1
import/batch_normalization_18/batchnorm_1/mul_2
import/batch_normalization_18/batchnorm_1/sub
import/batch_normalization_18/batchnorm_1/add_1
import/activation_18/Relu
import/up_sampling2d_3/Shape
import/up_sampling2d_3/strided_slice/stack
import/up_sampling2d_3/strided_slice/stack_1
import/up_sampling2d_3/strided_slice/stack_2
import/up_sampling2d_3/strided_slice
import/up_sampling2d_3/Const
import/up_sampling2d_3/mul
import/up_sampling2d_3/ResizeNearestNeighbor
import/concatenate_3/concat/axis
import/concatenate_3/concat
import/conv2d_19/kernel
import/conv2d_19/kernel/read
import/conv2d_19/bias
import/conv2d_19/bias/read
import/conv2d_19/convolution
import/conv2d_19/BiasAdd
import/batch_normalization_19/gamma
import/batch_normalization_19/gamma/read
import/batch_normalization_19/beta
import/batch_normalization_19/beta/read
import/batch_normalization_19/moving_mean
import/batch_normalization_19/moving_mean/read
import/batch_normalization_19/moving_variance
import/batch_normalization_19/moving_variance/read
import/batch_normalization_19/batchnorm_1/add/y
import/batch_normalization_19/batchnorm_1/add
import/batch_normalization_19/batchnorm_1/Rsqrt
import/batch_normalization_19/batchnorm_1/mul
import/batch_normalization_19/batchnorm_1/mul_1
import/batch_normalization_19/batchnorm_1/mul_2
import/batch_normalization_19/batchnorm_1/sub
import/batch_normalization_19/batchnorm_1/add_1
import/activation_19/Relu
import/conv2d_20/kernel
import/conv2d_20/kernel/read
import/conv2d_20/bias
import/conv2d_20/bias/read
import/conv2d_20/convolution
import/conv2d_20/BiasAdd
import/batch_normalization_20/gamma
import/batch_normalization_20/gamma/read
import/batch_normalization_20/beta
import/batch_normalization_20/beta/read
import/batch_normalization_20/moving_mean
import/batch_normalization_20/moving_mean/read
import/batch_normalization_20/moving_variance
import/batch_normalization_20/moving_variance/read
import/batch_normalization_20/batchnorm_1/add/y
import/batch_normalization_20/batchnorm_1/add
import/batch_normalization_20/batchnorm_1/Rsqrt
import/batch_normalization_20/batchnorm_1/mul
import/batch_normalization_20/batchnorm_1/mul_1
import/batch_normalization_20/batchnorm_1/mul_2
import/batch_normalization_20/batchnorm_1/sub
import/batch_normalization_20/batchnorm_1/add_1
import/activation_20/Relu
import/conv2d_21/kernel
import/conv2d_21/kernel/read
import/conv2d_21/bias
import/conv2d_21/bias/read
import/conv2d_21/convolution
import/conv2d_21/BiasAdd
import/batch_normalization_21/gamma
import/batch_normalization_21/gamma/read
import/batch_normalization_21/beta
import/batch_normalization_21/beta/read
import/batch_normalization_21/moving_mean
import/batch_normalization_21/moving_mean/read
import/batch_normalization_21/moving_variance
import/batch_normalization_21/moving_variance/read
import/batch_normalization_21/batchnorm_1/add/y
import/batch_normalization_21/batchnorm_1/add
import/batch_normalization_21/batchnorm_1/Rsqrt
import/batch_normalization_21/batchnorm_1/mul
import/batch_normalization_21/batchnorm_1/mul_1
import/batch_normalization_21/batchnorm_1/mul_2
import/batch_normalization_21/batchnorm_1/sub
import/batch_normalization_21/batchnorm_1/add_1
import/activation_21/Relu
import/up_sampling2d_4/Shape
import/up_sampling2d_4/strided_slice/stack
import/up_sampling2d_4/strided_slice/stack_1
import/up_sampling2d_4/strided_slice/stack_2
import/up_sampling2d_4/strided_slice
import/up_sampling2d_4/Const
import/up_sampling2d_4/mul
import/up_sampling2d_4/ResizeNearestNeighbor
import/concatenate_4/concat/axis
import/concatenate_4/concat
import/conv2d_22/kernel
import/conv2d_22/kernel/read
import/conv2d_22/bias
import/conv2d_22/bias/read
import/conv2d_22/convolution
import/conv2d_22/BiasAdd
import/batch_normalization_22/gamma
import/batch_normalization_22/gamma/read
import/batch_normalization_22/beta
import/batch_normalization_22/beta/read
import/batch_normalization_22/moving_mean
import/batch_normalization_22/moving_mean/read
import/batch_normalization_22/moving_variance
import/batch_normalization_22/moving_variance/read
import/batch_normalization_22/batchnorm_1/add/y
import/batch_normalization_22/batchnorm_1/add
import/batch_normalization_22/batchnorm_1/Rsqrt
import/batch_normalization_22/batchnorm_1/mul
import/batch_normalization_22/batchnorm_1/mul_1
import/batch_normalization_22/batchnorm_1/mul_2
import/batch_normalization_22/batchnorm_1/sub
import/batch_normalization_22/batchnorm_1/add_1
import/activation_22/Relu
import/conv2d_23/kernel
import/conv2d_23/kernel/read
import/conv2d_23/bias
import/conv2d_23/bias/read
import/conv2d_23/convolution
import/conv2d_23/BiasAdd
import/batch_normalization_23/gamma
import/batch_normalization_23/gamma/read
import/batch_normalization_23/beta
import/batch_normalization_23/beta/read
import/batch_normalization_23/moving_mean
import/batch_normalization_23/moving_mean/read
import/batch_normalization_23/moving_variance
import/batch_normalization_23/moving_variance/read
import/batch_normalization_23/batchnorm_1/add/y
import/batch_normalization_23/batchnorm_1/add
import/batch_normalization_23/batchnorm_1/Rsqrt
import/batch_normalization_23/batchnorm_1/mul
import/batch_normalization_23/batchnorm_1/mul_1
import/batch_normalization_23/batchnorm_1/mul_2
import/batch_normalization_23/batchnorm_1/sub
import/batch_normalization_23/batchnorm_1/add_1
import/activation_23/Relu
import/conv2d_24/kernel
import/conv2d_24/kernel/read
import/conv2d_24/bias
import/conv2d_24/bias/read
import/conv2d_24/convolution
import/conv2d_24/BiasAdd
import/batch_normalization_24/gamma
import/batch_normalization_24/gamma/read
import/batch_normalization_24/beta
import/batch_normalization_24/beta/read
import/batch_normalization_24/moving_mean
import/batch_normalization_24/moving_mean/read
import/batch_normalization_24/moving_variance
import/batch_normalization_24/moving_variance/read
import/batch_normalization_24/batchnorm_1/add/y
import/batch_normalization_24/batchnorm_1/add
import/batch_normalization_24/batchnorm_1/Rsqrt
import/batch_normalization_24/batchnorm_1/mul
import/batch_normalization_24/batchnorm_1/mul_1
import/batch_normalization_24/batchnorm_1/mul_2
import/batch_normalization_24/batchnorm_1/sub
import/batch_normalization_24/batchnorm_1/add_1
import/activation_24/Relu
import/up_sampling2d_5/Shape
import/up_sampling2d_5/strided_slice/stack
import/up_sampling2d_5/strided_slice/stack_1
import/up_sampling2d_5/strided_slice/stack_2
import/up_sampling2d_5/strided_slice
import/up_sampling2d_5/Const
import/up_sampling2d_5/mul
import/up_sampling2d_5/ResizeNearestNeighbor
import/concatenate_5/concat/axis
import/concatenate_5/concat
import/conv2d_25/kernel
import/conv2d_25/kernel/read
import/conv2d_25/bias
import/conv2d_25/bias/read
import/conv2d_25/convolution
import/conv2d_25/BiasAdd
import/batch_normalization_25/gamma
import/batch_normalization_25/gamma/read
import/batch_normalization_25/beta
import/batch_normalization_25/beta/read
import/batch_normalization_25/moving_mean
import/batch_normalization_25/moving_mean/read
import/batch_normalization_25/moving_variance
import/batch_normalization_25/moving_variance/read
import/batch_normalization_25/batchnorm_1/add/y
import/batch_normalization_25/batchnorm_1/add
import/batch_normalization_25/batchnorm_1/Rsqrt
import/batch_normalization_25/batchnorm_1/mul
import/batch_normalization_25/batchnorm_1/mul_1
import/batch_normalization_25/batchnorm_1/mul_2
import/batch_normalization_25/batchnorm_1/sub
import/batch_normalization_25/batchnorm_1/add_1
import/activation_25/Relu
import/conv2d_26/kernel
import/conv2d_26/kernel/read
import/conv2d_26/bias
import/conv2d_26/bias/read
import/conv2d_26/convolution
import/conv2d_26/BiasAdd
import/batch_normalization_26/gamma
import/batch_normalization_26/gamma/read
import/batch_normalization_26/beta
import/batch_normalization_26/beta/read
import/batch_normalization_26/moving_mean
import/batch_normalization_26/moving_mean/read
import/batch_normalization_26/moving_variance
import/batch_normalization_26/moving_variance/read
import/batch_normalization_26/batchnorm_1/add/y
import/batch_normalization_26/batchnorm_1/add
import/batch_normalization_26/batchnorm_1/Rsqrt
import/batch_normalization_26/batchnorm_1/mul
import/batch_normalization_26/batchnorm_1/mul_1
import/batch_normalization_26/batchnorm_1/mul_2
import/batch_normalization_26/batchnorm_1/sub
import/batch_normalization_26/batchnorm_1/add_1
import/activation_26/Relu
import/conv2d_27/kernel
import/conv2d_27/kernel/read
import/conv2d_27/bias
import/conv2d_27/bias/read
import/conv2d_27/convolution
import/conv2d_27/BiasAdd
import/batch_normalization_27/gamma
import/batch_normalization_27/gamma/read
import/batch_normalization_27/beta
import/batch_normalization_27/beta/read
import/batch_normalization_27/moving_mean
import/batch_normalization_27/moving_mean/read
import/batch_normalization_27/moving_variance
import/batch_normalization_27/moving_variance/read
import/batch_normalization_27/batchnorm_1/add/y
import/batch_normalization_27/batchnorm_1/add
import/batch_normalization_27/batchnorm_1/Rsqrt
import/batch_normalization_27/batchnorm_1/mul
import/batch_normalization_27/batchnorm_1/mul_1
import/batch_normalization_27/batchnorm_1/mul_2
import/batch_normalization_27/batchnorm_1/sub
import/batch_normalization_27/batchnorm_1/add_1
import/activation_27/Relu
import/conv2d_28/kernel
import/conv2d_28/kernel/read
import/conv2d_28/bias
import/conv2d_28/bias/read
import/conv2d_28/convolution
import/conv2d_28/BiasAdd
import/conv2d_28/Sigmoid
```

**Comment by aseemw** [comment]
As you can see `Sigmoid:0` is **not** in the list of tensors, hence the error.
It seems you should provide `conv2d_28/Sigmoid:0` instead

**Comment by Spectra456** [comment]
> As you can see `Sigmoid:0` is **not** in the list of tensors, hence the error.
> It seems you should provide `output_tensor_names = ['conv2d_28/Sigmoid:0']` instead

You are my hero, th.
