### ISSUE TITLE
Convert Facenet to CoreML

### ISSUE THREAD

**Issue by ramiro-feria-puron** [tf-coreml/tf-coreml#269]
I'm trying to convert a pre-trained model (TensorFlow) created by David Sandberg as part of the FaceNet (https://github.com/davidsandberg/facenet) project. Here is my conversion code:

`import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = '20180402-114759.pb',
                     mlmodel_path = 'Test.mlmodel',
                     output_feature_names = ['embeddings:0'],
                     input_name_shape_dict = {'batch_size:0':[1,160,160,3], 'phase_train:0':[]},
                     image_input_names = ['batch_size:0'],
                     red_bias = -1,
                     green_bias = -1,
                     blue_bias = -1,
                     image_scale = 2.0/255.0)`

And have tried a few variants for `input_name_shape_dict` unsuccessfully as well, such as:

`input_name_shape_dict = {'batch_size:0':[1,160,160,3]},
input_name_shape_dict = {'batch_size:0':[1,160,160,3], 'phase_train:0':[1]},
input_name_shape_dict = {'batch_size:0':[1,160,160,3], 'phase_train:0':[1,1,1,1]},`

each of them producing one or another shape error.

If anyone could provide some help on how to conert the model successfully it would be truly appreciated!!!

**Comment by ramiro-feria-puron** [comment]
Here are the model's operations summary:

OPS counts:
FIFOQueueV2 : 1
QueueDequeueUpToV2 : 1
AvgPool : 1
StridedSlice : 1
Pack : 1
RandomUniform : 1
Floor : 1
RealDiv : 1
MatMul : 1
Square : 1
Sum : 1
Maximum : 1
Rsqrt : 1
Placeholder : 2
MaxPool : 3
Shape : 3
Reshape : 3
BiasAdd : 21
ConcatV2 : 23
Add : 23
Relu : 131
Conv2D : 132
FusedBatchNorm : 224
Mul : 248
Merge : 449
Sub : 449
Identity : 1056
Const : 1104
Switch : 2019

**Comment by aseemw** [comment]
another useful tool to transform the graph is: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md

**Comment by ramiro-feria-puron** [comment]
Thanks @aseemw !

The Graph Transform Tool on the frozen graph removes most unsupported operations, but still has all the Switch operations:

>OPS counts:
AvgPool : 1
StridedSlice : 1
Pack : 1
RandomUniform : 1
Floor : 1
RealDiv : 1
MatMul : 1
Square : 1
Sum : 1
Maximum : 1
Rsqrt : 1
Placeholder : 2
MaxPool : 3
Shape : 3
Reshape : 3
BiasAdd : 21
ConcatV2 : 23
Add : 23
Relu : 131
Conv2D : 132
FusedBatchNorm : 224
Mul : 248
Merge : 449
Sub : 449
Identity : 1053
Const : 1104
Switch : 2019

I am using the transform
```
--transforms='
  strip_unused_nodes(type=float, shape="1,160,160,3")
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  round_weights(num_steps=256)'
```
Not sure on why the arguments for the strip_unused_nodes though. And then `tfcoreml.convert` exits with this error:

```
Traceback (most recent call last):
  File "convert.py", line 5, in <module>
    output_feature_names = ['import/embeddings:0'])
  File "/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 586, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 243, in _convert_pb_to_mlmodel
    tensors_evaluated = sess.run(tensors, feed_dict=input_feed_dict)
  File "/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/anaconda3/envs/tensorflow_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[4] does not have value
```

**Comment by vonholst** [comment]
I used a Keras implementation: https://github.com/nyoki-mtl/keras-facenet

There is a notebook there to transfer weights from the model you are trying to convert as well. You need to write one custom layer in Swift, but it's a trivial scaling layer.

I used it with iOS Vision-framework for the face-detection part. Works lika a charm.

Best of luck!

**Comment by ramiro-feria-puron** [comment]
@vonholst Awesome!!! Thanks a lot!

Almost there; just having one issue while comparing embeddings. Thought that you would probably have some answer:

The output vectors from the model are not normalized. Is it supposed to be the case? I get lengths around 17, 23, etc. If I normalize them I still get "consistent" results; that is, for positive pairs the distance is say somewhere between .200 and .300, whereas for negative ones it ranges between .400 and .500. Roughly speaking. But this is not consistent with what is supposed to be the actual threshold.

I have implemented my `scaling` Custom Layer in Swift, and I can see the values for the `scale` parameter coming are the same as in `inception_resnet_v1.py`.

Best regards,
Ramiro

**Comment by scm-ns** [comment]
@aseemw Hey, if I wanted to write a custom core ml layer for Switch, Merge, the control flow ops, is that possible? Is there something in the CoreML framework preventing that? Those ops seem pretty straight forward to implement.

**Comment by aseemw** [comment]
Here is the Custom Layer API: https://developer.apple.com/documentation/coreml/mlcustomlayer?language=objc

Any layer that fits this API can be a custom layer: fixed output shape given input shape and the implementation. Switch, Merge/control flow would be hard to implement using this API.

**Comment by wangdan0527** [comment]
@vonholst 

Hi.
How are you today?
I used Keras implementation as you did and converted h5 to coreml.

I used this script.

https://gist.github.com/viteinfinite/1901d9cb6d26c21967a08aa5534e05c2

On the iOS application, the coreml output result is nil.

![image](https://user-images.githubusercontent.com/19706426/65347253-36980d00-dc11-11e9-8467-93968a1fa85a.png)

I experienced such issue for coreml converted from facenet protobuf model.
Can you please give me your opinion?

Thanks

**Comment by wangdan0527** [comment]
@ramiro-feria-puron 

Hi.

How are you today?
Did you find a solution for normalizing output vector of coreml converted from facenet model?

Thanks

**Comment by vonholst** [comment]
Hi, this was a while ago. I don’t recall having to normalize outputs. I used l2 norm or a knn model to determine classes. Either option works.

**Comment by Mstronach** [comment]
Can you please provide the latest build and let us know what issue you are facing, we would be happy to investigate this further. Thanks!
