### ISSUE TITLE
Error running convertor.py

### ISSUE THREAD

**Issue by kevinliao123** [tf-coreml/tf-coreml#271]
After installation, python convertor.py gives me error below. Please let me know if anyone can help.

`Loading the TF graph...
Traceback (most recent call last):
  File "convertor.py", line 4, in <module>
    output_feature_names = ['softmax:0'])
  File "/home/kev/Projects/tensor-flow/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 586, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/home/kev/Projects/tensor-flow/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 153, in _convert_pb_to_mlmodel
    tf.import_graph_def(gdef, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'TFLite_Detection_PostProcess' in binary running on kev-VirtualBox. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.`

**Comment by 1duo** [comment]
Hi @kevinliao123, thanks for reporting this issue! It seems the error is in the TensorFlow Lite framework? It's not quite clear what the issue is. If you're still facing this issue, can you [file a bug](https://github.com/tf-coreml/tf-coreml/issues/new?assignees=&labels=bug&template=--bug-report.md&title=) with detailed reproduce steps? Thanks!
