### ISSUE TITLE
Unhandled strided slice case

### ISSUE THREAD

**Issue by suoloordi** [tf-coreml/tf-coreml#277]
I'm having an issue with a strided slice op in a model i'm working on. 
This is the stack trace:
```
Traceback (most recent call last):
  File "convert.py", line 40, in <module>
    image_input_names=image_input_name)
  File "/home/baris/.virtualenvs/deepfigures/lib/python3.5/site-packages/tfcoreml/_tf_coreml_converter.py", line 586, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/home/baris/.virtualenvs/deepfigures/lib/python3.5/site-packages/tfcoreml/_tf_coreml_converter.py", line 337, in _convert_pb_to_mlmodel
    convert_ops_to_layers(context)
  File "/home/baris/.virtualenvs/deepfigures/lib/python3.5/site-packages/tfcoreml/_ops_to_layers.py", line 178, in convert_ops_to_layers
    translator(op, context)
  File "/home/baris/.virtualenvs/deepfigures/lib/python3.5/site-packages/tfcoreml/_layers.py", line 1269, in strided_slice
    assert False, ('Strided Slice case not handled. Input shape = {}, output shape = {}'.format(str(input_shape),str(output_shape)))
AssertionError: Strided Slice case not handled. Input shape = [1, 20, 15, 832], output shape = [1, 20, 15, 132]
```
I've printed out some related local variables to help pinpoint what the issue is:
```
input_shape:  [1, 20, 15, 832]
begin:  [  0   0   0 700]
strides:  [1 1 1 1]
end:  [0 0 0 0]
begin_mask:  7
end_mask:  15
```

Would it be possible to support strided slices of this form?

**Comment by lissyx** [comment]
Same here trying to export DeepSpeech model as CoreML:
```
AssertionError: Strided Slice case not handled. Input shape = [16, 1, 2048], output shape = [1, 2048]
```

**Comment by Mahanotrahul** [comment]
@suoloordi @lissyx Even I am having a similar problem.
```AssertionError: Strided Slice case not handled. Input shape = [1, 4, 26], output shape = [1, 3, 26]```

Did you find any workaround for this problem?

**Comment by lissyx** [comment]
Nope

**Comment by DawerG** [comment]
@lissyx For DeepSpeech model, it's possible to get rid of `stripped slice` op by using `strip_unused_lib.strip_unused` utility.

```import tensorflow as tf
from tensorflow.python.tools import strip_unused_lib
from tensorflow.python.framework import dtypes
from tensorflow.python.platform import gfile

tf_model_path = 'output_graph.pb'
with open(tf_model_path, 'rb') as f:
    serialized = f.read()
tf.reset_default_graph()
original_gdef = tf.GraphDef()
original_gdef.ParseFromString(serialized)


input_node_names = []
output_node_names = ['Softmax']
gdef = strip_unused_lib.strip_unused(
        input_graph_def = original_gdef,
        input_node_names = input_node_names,
        output_node_names = output_node_names,
        placeholder_type_enum = dtypes.float32.as_datatype_enum)
# Save it to an output file
frozen_model_file = './striped_frozen.pb'
with gfile.GFile(frozen_model_file, "wb") as f:
    f.write(gdef.SerializeToString()) ```

**Comment by lissyx** [comment]
> @lissyx For DeepSpeech model, it's possible to get rid of `strided slice` op by using `strip_unused_lib.strip_unused` utility.
> 
> ```
> from tensorflow.python.tools import strip_unused_lib
> from tensorflow.python.framework import dtypes
> from tensorflow.python.platform import gfile
> 
> tf_model_path = 'output_graph.pb'
> with open(tf_model_path, 'rb') as f:
>     serialized = f.read()
> tf.reset_default_graph()
> original_gdef = tf.GraphDef()
> original_gdef.ParseFromString(serialized)
> 
> 
> input_node_names = []
> output_node_names = ['Softmax']
> gdef = strip_unused_lib.strip_unused(
>         input_graph_def = original_gdef,
>         input_node_names = input_node_names,
>         output_node_names = output_node_names,
>         placeholder_type_enum = dtypes.float32.as_datatype_enum)
> # Save it to an output file
> frozen_model_file = './striped_frozen.pb'
> with gfile.GFile(frozen_model_file, "wb") as f:
>     f.write(gdef.SerializeToString()) ``` 
> ```

Interesting, last time I tried `strip_unused` it was not really doing any good. I'll give it a new try then!

**Comment by lissyx** [comment]
@DawerG As before, applying `strip_unused`, I still have the same list of ops in the output graph, including `StridedSlice`.

**Comment by 1duo** [comment]
@lissyx For deepspeech model, please refer to https://github.com/tf-coreml/tf-coreml/blob/master/examples/deep_speech.ipynb

**Comment by lissyx** [comment]
> @lissyx For deepspeech model, please refer to https://github.com/tf-coreml/tf-coreml/blob/master/examples/deep_speech.ipynb

Can you be more specific ? This is 0.4.1. Was the strided slice issue a bug on `tf-coreml` side that was fixed ?

**Comment by DawerG** [comment]
@suoloordi This particular example of strider-slice works fine. Can you please try building from the source?
