### ISSUE TITLE
tf_converter.convert Error

### ISSUE THREAD

**Issue by icaruslucifer** [tf-coreml/tf-coreml#298]
When I first run:
bazel-bin/tensorflow/tools/quantization/quantize_graph --input=/Users/icarus/Documents/icarusCode/Python/neural-style-transfer/fast-style-transfer-coreml-master/fast_style_transfer/checkpoints_test/output_graph.pb --output_node_names="add_37" --output=/Users/icarus/Documents/icarusCode/Python/neural-style-transfer/fast-style-transfer-coreml-master/fast_style_transfer/checkpoints_test/output_graph_ff.pb --mode=weights

pb file from 6.7M to 1.7M,
then:
tf_converter.convert(tf_model_path = '../checkpoints_test/output_graph_ff.pb',
                     mlmodel_path = '../checkpoints_test/udnie.mlmodel',
                     output_feature_names = ['add_37:0'],
                     image_input_names = ['img_placeholder__0'])

error info:

Traceback (most recent call last):
  File "/Users/icarus/Documents/icarusCode/Python/neural-style-transfer/fast-style-transfer-coreml-master/fast_style_transfer/convert_graph/convert.py", line 5, in <module>
    image_input_names = ['img_placeholder__0'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 586, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 337, in _convert_pb_to_mlmodel
    convert_ops_to_layers(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfcoreml/_ops_to_layers.py", line 178, in convert_ops_to_layers
    translator(op, context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfcoreml/_layers_common.py", line 77, in effectively_constant_op
    add_const(context, out.name, x, out.name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfcoreml/_layers_common.py", line 26, in add_const
    _add_const(context, name, x, output_name, shape)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfcoreml/_shape_sensitive_layers.py", line 44, in _add_const
    'Add constant: cannot add a constant in which all the dimensions ' \
AssertionError: Add constant: cannot add a constant in which all the dimensions (Seq, C, H, W) are of non-unit size

**Comment by 1duo** [comment]
Hi @icaruslucifer, thanks for reporting this issue! To clarify, the model you're converting is already quantized with TF? Can you [file a bug](https://github.com/tf-coreml/tf-coreml/issues/new?assignees=&labels=bug&template=--bug-report.md&title=) with detailed reproduce steps? Thanks!
