### ISSUE TITLE
Slicing not works after conversion succeed

### ISSUE THREAD

**Issue by bocsiboti** [tf-coreml/tf-coreml#304]
I have a simple graph (for image cropping) defined as follows:

```
X = tf.placeholder(shape=(1, 1280, 720, 3), dtype=tf.float32)
aux = X[:, :-1, :, :]
aux = tf.multiply(aux, 1, 'aux')
```
The conversion to protobuffer and to coreml model works fine:
```
Loading the TF graph...
Graph Loaded.
Collecting all the 'Const' ops from the graph, by running it....
Done.
Now finding ops in the TF graph that can be dropped for inference
Now starting translation to CoreML graph.
Automatic shape interpretation succeeded for input blob Placeholder:0
1/7: Analysing op name: aux/y ( type:  Const )
2/7: Analysing op name: strided_slice/stack_2 ( type:  Const )
3/7: Analysing op name: strided_slice/stack_1 ( type:  Const )
4/7: Analysing op name: strided_slice/stack ( type:  Const )
5/7: Analysing op name: Placeholder ( type:  Placeholder )
Skipping name of placeholder
6/7: Analysing op name: strided_slice ( type:  StridedSlice )
7/7: Analysing op name: aux ( type:  Mul )
Translation to CoreML spec completed. Now compiling and saving the CoreML model.

Core ML model generated. Saved at location: /home/ml-pc-2/tmp/tmp/model_0-1.mlmodel

Core ML input(s):
[name: "Placeholder__0"
type {
 imageType {
   width: 720
   height: 1280
   colorSpace: RGB
 }
}
]
Core ML output(s):
[name: "aux__0"
type {
 multiArrayType {
   shape: 3
   shape: 1279
   shape: 720
   dataType: DOUBLE
 }
}
]
```

However, when using the .mlmodel in Xcode, I get the following error:

`validator error: Layer 'aux:0' consumes an input named 'strided_slice:0' which is not present in this network.
`

When using the visualize_spec() coremltools function, I get the following error:
```
Traceback (most recent call last):
  File "vmodel.py", line 5, in <module>
    model.visualize_spec()
  File "/home/apple/.local/lib/python3.5/site-packages/coremltools/models/model.py", line 445, in visualize_spec
    input_shape_dict=input_shape_dict
  File "/home/apple/.local/lib/python3.5/site-packages/coremltools/models/_graph_visualization.py", line 672, in _neural_network_nodes_and_edges
    shape_dict = _infer_shapes(nn_spec, input_spec, input_shape_dict=input_shape_dict)
  File "/home/apple/.local/lib/python3.5/site-packages/coremltools/models/_infer_shapes_nn_mlmodel.py", line 458, in infer_shapes
    assert inp in shape_dict, ('Input %s shape not cannot be determined' %(inp))
AssertionError: Input strided_slice:0 shape not cannot be determined

```

I know that the StridedSlice and Slice operations are not fully supported but should not I get an error when coverting the model?

I also noticed that the error occurred only for a couple of slicing case.

Examples when it works:
```
aux = X[:, 1:, :, :]
aux = X[:, :, 1:, :]
aux = X[:, 1:, :-1, :]
aux = X[:, :-1, 1:, :]
aux = X[:, 1:, 1:, :]
```

Examples when I get an error:
```
aux = X[:, :-1, :, :]
aux = X[:, :-1, :-1, :]
aux = X[:, :, :-1, :]
```

I used the following tools:

- tensorflow==1.13.11
- protobuf==3.7.1
- coremltools==2.1.0
- tfcoreml==0.3.0 (also tried https://github.com/tf-coreml/tf-coreml and https://github.com/DawerG/tf-coreml, same results)

**Comment by DawerG** [comment]
@bocsiboti This particular example of strided-slice works fine. Can you please try building coremltools package from the source? Please use minimum_ios_deployment_target='13' while converting.
