### ISSUE TITLE
ValueError: Input 0 of node was passed float from other node:0 incompatible with expected resource

### ISSUE THREAD

**Issue by tucan9389** [tf-coreml/tf-coreml#307]
I tried to convert tf.keras model using pre-trained ResNet50 on head from frozen pb, but  ValueError (`ValueError: Input 0 of node resnet50/bn_conv1/cond/ReadVariableOp/Switch was passed float from bn_conv1/gamma:0 incompatible with expected resource.`) is occurred. 

Does anyone have any advice?

Thank you :-)

```
Traceback (most recent call last):
  File "/Users/doyounggwak/anaconda3/envs/tl-env/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 426, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node resnet50/bn_conv1/cond/ReadVariableOp/Switch was passed float from bn_conv1/gamma:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/doyounggwak/Project/MoTLabs/rehapp/ML/tf-pose-estimation-with-transfer-learning/convert_to_mlmodel.py", line 47, in <module>
    input_name_shape_dict = {'resnet50_input' : [1, 160, 160, 3]})
  File "/Users/doyounggwak/Project/MoTLabs/rehapp/ML/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 593, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/Users/doyounggwak/Project/MoTLabs/rehapp/ML/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 153, in _convert_pb_to_mlmodel
    tf.import_graph_def(gdef, name='')
  File "/Users/doyounggwak/anaconda3/envs/tl-env/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/doyounggwak/anaconda3/envs/tl-env/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: Input 0 of node resnet50/bn_conv1/cond/ReadVariableOp/Switch was passed float from bn_conv1/gamma:0 incompatible with expected resource.

Process finished with exit code 1
```

**Comment by tucan9389** [comment]
### resnet50/bn_conv1/cond/ReadVariableOp/Switch node
<img width="892" alt="Screen Shot 2019-06-05 at 9 36 43 AM" src="https://user-images.githubusercontent.com/37643248/58922347-7677d900-8775-11e9-8167-c9edea316688.png">

### resnet50/bn_conv1/cond/ReadVariableOp node
<img width="892" alt="Screen Shot 2019-06-05 at 9 36 47 AM" src="https://user-images.githubusercontent.com/37643248/58922366-7ed01400-8775-11e9-95e7-c4d806ba0141.png">

**Comment by Zhiwei35** [comment]
@tucan9389 hi, did you solve the problem? i meet a similar question with you. plz help. thanks.
