### ISSUE TITLE
Unable to convert .pb 

### ISSUE THREAD

**Issue by veeeencedamico2** [tf-coreml/tf-coreml#312]
```
import tfcoreml as tf_converter

tf_converter.convert(tf_model_path = 'my_model.pb', 
                     mlmodel_path = 'my_model.mlmodel', 
                     output_feature_names = ["EncodeJpeg:0"],
                     use_coreml_3 = True)
```

Result:

```
Type 20 cannot be mapped
Type 20 cannot be mapped
0 assert nodes deleted
Fixing frame name: map_4/while/while_context
2019-06-15 15:11:40.579592: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
77 nodes deleted
('main', u'map_4/while/maximum_iterations') cond_function_0
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u32/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u32/instance_norm/moments/SquaredDifference (SquaredDifference)
Unable to infer type of node G_7/u32/instance_norm/moments/variance (Mean)
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u64/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u64/instance_norm/moments/SquaredDifference (SquaredDifference)
Unable to infer type of node G_7/u64/instance_norm/moments/variance (Mean)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u64/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u64/instance_norm/moments/SquaredDifference (SquaredDifference)
Unable to infer type of node G_7/u64/instance_norm/moments/variance (Mean)
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op EncodeJpeg Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u32/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u32/instance_norm/moments/SquaredDifference (SquaredDifference)
Op EncodeJpeg Not implemented
Unable to infer type of node output_image (Identity)
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u32/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u32/instance_norm/moments/SquaredDifference (SquaredDifference)
Unable to infer type of node G_7/u32/instance_norm/moments/variance (Mean)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u64/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u64/instance_norm/moments/SquaredDifference (SquaredDifference)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u64/instance_norm/moments/StopGradient (Identity)
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u32/instance_norm/moments/StopGradient (Identity)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u64/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u64/instance_norm/moments/SquaredDifference (SquaredDifference)
Unable to infer type of node G_7/u64/instance_norm/moments/variance (Mean)
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op EncodeJpeg Not implemented
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u32/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u32/instance_norm/moments/SquaredDifference (SquaredDifference)
Op EncodeJpeg Not implemented
Unable to infer type of node output_image (Identity)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u32/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u32/instance_norm/moments/SquaredDifference (SquaredDifference)
Unable to infer type of node G_7/u32/instance_norm/moments/variance (Mean)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u64/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u64/instance_norm/moments/SquaredDifference (SquaredDifference)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u64/instance_norm/moments/StopGradient (Identity)
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u32/instance_norm/moments/StopGradient (Identity)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u64/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u64/instance_norm/moments/SquaredDifference (SquaredDifference)
Unable to infer type of node G_7/u64/instance_norm/moments/variance (Mean)
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op EncodeJpeg Not implemented
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u32/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u32/instance_norm/moments/SquaredDifference (SquaredDifference)
Op EncodeJpeg Not implemented
Unable to infer type of node output_image (Identity)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u32/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u32/instance_norm/moments/SquaredDifference (SquaredDifference)
Unable to infer type of node G_7/u32/instance_norm/moments/variance (Mean)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u64/instance_norm/moments/StopGradient (Identity)
Unable to infer type of node G_7/u64/instance_norm/moments/SquaredDifference (SquaredDifference)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u64/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u64/instance_norm/moments/StopGradient (Identity)
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Unable to infer type of node G_7/u32/instance_norm/moments/mean (Mean)
Unable to infer type of node G_7/u32/instance_norm/moments/StopGradient (Identity)
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op MirrorPad Not implemented
Op Conv2DBackpropInput Not implemented
Op MirrorPad Not implemented
1 nodes deleted
0 nodes deleted
Traceback (most recent call last):
  File "coreml.py", line 6, in <module>
    use_coreml_3 = True)
  File "/usr/local/lib/python2.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 594, in convert
    outputs=output_feature_names)
  File "/usr/local/lib/python2.7/site-packages/coremltools/converters/tensorflow/_tf_converter.py", line 11, in convert
    ssa = frontend_load(filename, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/coremltools/converters/nnssa/frontend/tensorflow/load.py", line 70, in load
    assert (n.datatype is not None)
AssertionError
```

**Comment by b-onc** [comment]
I also get the same `Type 20 cannot be mapped`, although the rest is different

**Comment by edis219** [comment]
Encounter the same issue, when convert TF to CoreML

**Comment by 1duo** [comment]
@veeeencedamico2 @b-onc @edis219 Although error message (`Type 20 cannot be mapped`) may seems similar but the error might actually happens during converting different TF ops. It'd be extremely helpful if you could share your model (a link to the frozen TF `.pb` file) and conversion scripts. This way, we can reproduce the error and we're happy to help to fix any missing ops and convert the model. Feel free to leave a comment here or open a new issue. Thanks!

**Comment by SanthoshRajendiran** [comment]
This happens even with the default deeplab model hosted in tensorflow github page. We are not able to convert the deeplab model.

**Comment by 1duo** [comment]
> This happens even with the default deeplab model hosted in tensorflow github page. We are not able to convert the deeplab model.

Hi @SanthoshRajendiran, thanks for reporting the issue! FYI, we have a DeepLab Core ML model here: https://developer.apple.com/machine-learning/models/. In the meantime, we'll investigate the conversion for the TensorFlow GitHub page.  Feel free to re-open / [file a bug](https://github.com/tf-coreml/tf-coreml/issues/new?assignees=&labels=bug&template=--bug-report.md&title=) if you hit any specific issues.
