### ISSUE TITLE
Segmentation fault in loading .mlmodel on MacOS

### ISSUE THREAD

**Issue by naoto0804** [tf-coreml/tf-coreml#313]
I converted my tensorflow frozen model (.pb) to coreml by `tf_converter.convert` in Ubuntu.
It seems it successfully converted according to the log, but when I try to load my model in MacOS (for testing `.predict` function), it throws a segmentation fault error. Is there any way to investigate what's wrong?

**System information (converting)**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow version: 1.4.0
- Python version: 3.7.3
- coremltools==3.0b1
**System information (testing)**
- OS Platform and Distribution: Mac OS 10.14.5
- Python version: 3.7.3
- coremltools==3.0b1

**Comment by cuculesa** [comment]
Can you share the model with us? Thank you.

**Comment by naoto0804** [comment]
Thank you for helping, but I cannot share the model due to NDA (was during the internship at a company), so sorry for that.

**Comment by aseemw** [comment]
Hi @naoto0804, in that case, there is also an option of filing an official bug report at https://developer.apple.com/bug-reporting/, through which you can privately share your model. 

Another option is if you could construct a model with similar architecture but random weights, such that the issue is reproduced on this toy model, then that we can reproduce and look into the issue.

**Comment by dhananjaisharma10** [comment]
> I converted my tensorflow frozen model (.pb) to coreml by `tf_converter.convert` in Ubuntu.
> It seems it successfully converted according to the log, but when I try to load my model in MacOS (for testing `.predict` function), it throws a segmentation fault error. Is there any way to investigate what's wrong?
> 
> **System information (converting)**
> 
> * OS Platform and Distribution: Linux Ubuntu 16.04
> * TensorFlow version: 1.4.0
> * Python version: 3.7.3
> * coremltools==3.0b1
> 
> **System information (testing)**
> 
> * OS Platform and Distribution: Mac OS 10.14.5
> * Python version: 3.7.3
> * coremltools==3.0b1

Facing a similar issue. But I had done the entire process on MacOS.

**System information**
OS Platform and Distribution: macOS Mojave 10.14.6
TensorFlow version: 1.14.0
Python version: 3.7.3
coremltools==3.0b5
tfcoreml==0.4.0b1

**Code to reproduce the issue**
```python
import os.path as osp

import tfcoreml
import tempfile
import shutil
import coremltools
import numpy as np
import tensorflow as tf

# You might find it useful to work inside the
# tpu/models/official/mnasnet/mixnet/ directory
from mixnet_builder import build_model
from tensorflow.compat.v1 import graph_util
from tensorflow.python.tools.freeze_graph import freeze_graph

def _freeze_graph(model_direc, output_node_names, frozen_file):
    r"""This function freezes the graph and saves it as a .pb file
    Args:
        - model_direc (str): directory containing the checkpoint
        - output_node_names (list): name of the output nodes of the model.
            This allows TF to extract the part of the graph desired for
            evaluation.
        - frozen_file (str): save the frozen file under this name
    """

    # Retrieve our checkpoint fullpath
    checkpoint = tf.train.get_checkpoint_state(model_direc)
    input_checkpoint = checkpoint.model_checkpoint_path
    output_graph = frozen_file
    # Allow TF to control on which device it will load operations
    clear_devices = True
    # Import the meta graph and retrieve a Saver
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta',
                                       clear_devices=clear_devices)
    # Retrieve the protobuf graph definition
    graph = tf.get_default_graph()
    input_graph_def = graph.as_graph_def()
    # Start a session and restore the graph weights
    with tf.Session() as sess:
        saver.restore(sess, input_checkpoint)
        # Use a built-in TF helper to export variables to constants
        output_graph_def = graph_util.convert_variables_to_constants(
            sess,  # Session is used to retrieve the weights
            input_graph_def,  # Graph_def is used to retrieve the nodes
            output_node_names
        )
        # Serialize and dump the output graph to the filesystem
        with tf.gfile.GFile(output_graph, "wb") as f:
            f.write(output_graph_def.SerializeToString())
        print("%d ops in the final graph." % len(output_graph_def.node))
    # visualize the frozen TF model
    # _visualize(frozen_file, np.random.randint(8000, 9000))


# A utility function to freeze rhe graph. It will be used later
def _simple_run_and_freeze(graph,
                           output_name,
                           frozen_model_file='',
                           feed_dict={}):
    model_dir = tempfile.mkdtemp()
    graph_def_file = osp.join(model_dir, 'tf_graph.pbtxt')
    checkpoint_file = osp.join(model_dir, 'tf_model.ckpt')

    tf.reset_default_graph()
    with graph.as_default() as g:
        saver = tf.train.Saver()
    with tf.Session(graph=graph) as sess:
        # initialize
        sess.run(tf.global_variables_initializer())
        # run the result
        fetch = graph.get_operation_by_name(output_name).outputs[0]
        tf_result = sess.run(fetch, feed_dict=feed_dict)
        # save graph definition somewhere
        tf.train.write_graph(sess.graph, model_dir, graph_def_file)
        # save the weights
        saver.save(sess, checkpoint_file)

    freeze_graph(input_graph=graph_def_file,
                 input_saver="",
                 input_binary=False,
                 input_checkpoint=checkpoint_file,
                 output_node_names=output_name,
                 restore_op_name="save/restore_all",
                 filename_tensor_name="save/Const:0",
                 output_graph=frozen_model_file,
                 clear_devices=True,
                 initializer_nodes="")

    if osp.exists(model_dir):
        shutil.rmtree(model_dir)

    return tf_result


def convert(frozen_model, ml_model):
    dim1 = 224
    dim2 = 224
    coreml_model = tfcoreml.convert(tf_model_path=frozen_model,
                                    mlmodel_path=ml_model,
                                    output_feature_names=['logits:0'],
                                    input_name_shape_dict={'X:0': [20, dim1,
                                                                   dim2, 3]},
                                    image_input_names=['X:0'],
                                    add_custom_layers=True)
    img = np.random.randn(20, dim1, dim2, 3)
    coreml_inputs = {'X__0': img}
    coreml_output = coreml_model.predict(coreml_inputs, useCPUOnly=True)
    print(coreml_output)
    # visualize CoreML model
    # _visualize(ml_model, np.random.randint(8000, 9000))
    # inspect the CoreML model
    # spec = coreml_model.get_spec()
    # _print_coreml_nn_layer_info(spec)


if __name__ == '__main__':
    BATCH_SIZE = 20
    DIM1 = DIM2 = 224
    tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
    base_directory = './mixnet_weights_bn'  # directory containing the ckpt
    if not osp.exists(base_directory):
        raise AssertionError('Checkpoint {} does not exist'.format(
                             base_directory))
    frozen_model = 'mixnet.pb'
    frozen_model = osp.join(base_directory, frozen_model)
    out_names = ['logits']
    method = 'tfi'  # change method to 'tf' to use function _simple_run_and_freeze
    if method == 'tf':
        # define a TF graph: input -> MixNet -> output
        graph = tf.Graph()
        with graph.as_default() as g:
            inputs = tf.placeholder(tf.float32,
                                    shape=[BATCH_SIZE, DIM1, DIM2, 3],
                                    name='X')
            logits, _ = build_model(inputs, 'mixnet-s', False)

        output_name = logits.op.name
        X = np.random.randn(BATCH_SIZE, DIM1, DIM2, 3)
        frozen_model_file = 'mixnet_s_graph.pb'
        coreml_model_path = 'mixnet_s_graph.mlmodel'
        out = _simple_run_and_freeze(graph,
                                     output_name,
                                     frozen_model_file,
                                     feed_dict={'X:0': X})
    else:
        # Freeze graph
        _freeze_graph(base_directory, out_names, frozen_model)
    if not osp.isfile(frozen_model):
        raise AssertionError('Graph {} could not be frozen.'.format(
                             frozen_model))
    ml_model = 'mixnet_coreml.mlmodel'
    ml_model = osp.join(base_directory, ml_model)
    # Convert to Core ML
    convert(frozen_model, ml_model)
    if not osp.isfile(ml_model):
        raise AssertionError('Core ML model {} not found.'.format(ml_model))
```

Please help me out and let me know in case you need any further information. Thanks!

**Comment by 1duo** [comment]
> > I converted my tensorflow frozen model (.pb) to coreml by `tf_converter.convert` in Ubuntu.
> > It seems it successfully converted according to the log, but when I try to load my model in MacOS (for testing `.predict` function), it throws a segmentation fault error. Is there any way to investigate what's wrong?
> > **System information (converting)**
> > 
> > * OS Platform and Distribution: Linux Ubuntu 16.04
> > * TensorFlow version: 1.4.0
> > * Python version: 3.7.3
> > * coremltools==3.0b1
> > 
> > **System information (testing)**
> > 
> > * OS Platform and Distribution: Mac OS 10.14.5
> > * Python version: 3.7.3
> > * coremltools==3.0b1
> 
> Facing a similar issue. But I had done the entire process on MacOS.
> 
> **System information**
> OS Platform and Distribution: macOS Mojave 10.14.6
> TensorFlow version: 1.14.0
> Python version: 3.7.3
> coremltools==3.0b5
> tfcoreml==0.4.0b1
> 
> **Code to reproduce the issue**
> 
> ```python
> import os.path as osp
> 
> import tfcoreml
> import tempfile
> import shutil
> import coremltools
> import numpy as np
> import tensorflow as tf
> 
> # You might find it useful to work inside the
> # tpu/models/official/mnasnet/mixnet/ directory
> from mixnet_builder import build_model
> from tensorflow.compat.v1 import graph_util
> from tensorflow.python.tools.freeze_graph import freeze_graph
> 
> def _freeze_graph(model_direc, output_node_names, frozen_file):
>     r"""This function freezes the graph and saves it as a .pb file
>     Args:
>         - model_direc (str): directory containing the checkpoint
>         - output_node_names (list): name of the output nodes of the model.
>             This allows TF to extract the part of the graph desired for
>             evaluation.
>         - frozen_file (str): save the frozen file under this name
>     """
> 
>     # Retrieve our checkpoint fullpath
>     checkpoint = tf.train.get_checkpoint_state(model_direc)
>     input_checkpoint = checkpoint.model_checkpoint_path
>     output_graph = frozen_file
>     # Allow TF to control on which device it will load operations
>     clear_devices = True
>     # Import the meta graph and retrieve a Saver
>     saver = tf.train.import_meta_graph(input_checkpoint + '.meta',
>                                        clear_devices=clear_devices)
>     # Retrieve the protobuf graph definition
>     graph = tf.get_default_graph()
>     input_graph_def = graph.as_graph_def()
>     # Start a session and restore the graph weights
>     with tf.Session() as sess:
>         saver.restore(sess, input_checkpoint)
>         # Use a built-in TF helper to export variables to constants
>         output_graph_def = graph_util.convert_variables_to_constants(
>             sess,  # Session is used to retrieve the weights
>             input_graph_def,  # Graph_def is used to retrieve the nodes
>             output_node_names
>         )
>         # Serialize and dump the output graph to the filesystem
>         with tf.gfile.GFile(output_graph, "wb") as f:
>             f.write(output_graph_def.SerializeToString())
>         print("%d ops in the final graph." % len(output_graph_def.node))
>     # visualize the frozen TF model
>     # _visualize(frozen_file, np.random.randint(8000, 9000))
> 
> 
> # A utility function to freeze rhe graph. It will be used later
> def _simple_run_and_freeze(graph,
>                            output_name,
>                            frozen_model_file='',
>                            feed_dict={}):
>     model_dir = tempfile.mkdtemp()
>     graph_def_file = osp.join(model_dir, 'tf_graph.pbtxt')
>     checkpoint_file = osp.join(model_dir, 'tf_model.ckpt')
> 
>     tf.reset_default_graph()
>     with graph.as_default() as g:
>         saver = tf.train.Saver()
>     with tf.Session(graph=graph) as sess:
>         # initialize
>         sess.run(tf.global_variables_initializer())
>         # run the result
>         fetch = graph.get_operation_by_name(output_name).outputs[0]
>         tf_result = sess.run(fetch, feed_dict=feed_dict)
>         # save graph definition somewhere
>         tf.train.write_graph(sess.graph, model_dir, graph_def_file)
>         # save the weights
>         saver.save(sess, checkpoint_file)
> 
>     freeze_graph(input_graph=graph_def_file,
>                  input_saver="",
>                  input_binary=False,
>                  input_checkpoint=checkpoint_file,
>                  output_node_names=output_name,
>                  restore_op_name="save/restore_all",
>                  filename_tensor_name="save/Const:0",
>                  output_graph=frozen_model_file,
>                  clear_devices=True,
>                  initializer_nodes="")
> 
>     if osp.exists(model_dir):
>         shutil.rmtree(model_dir)
> 
>     return tf_result
> 
> 
> def convert(frozen_model, ml_model):
>     dim1 = 224
>     dim2 = 224
>     coreml_model = tfcoreml.convert(tf_model_path=frozen_model,
>                                     mlmodel_path=ml_model,
>                                     output_feature_names=['logits:0'],
>                                     input_name_shape_dict={'X:0': [20, dim1,
>                                                                    dim2, 3]},
>                                     image_input_names=['X:0'],
>                                     add_custom_layers=True)
>     img = np.random.randn(20, dim1, dim2, 3)
>     coreml_inputs = {'X__0': img}
>     coreml_output = coreml_model.predict(coreml_inputs, useCPUOnly=True)
>     print(coreml_output)
>     # visualize CoreML model
>     # _visualize(ml_model, np.random.randint(8000, 9000))
>     # inspect the CoreML model
>     # spec = coreml_model.get_spec()
>     # _print_coreml_nn_layer_info(spec)
> 
> 
> if __name__ == '__main__':
>     BATCH_SIZE = 20
>     DIM1 = DIM2 = 224
>     tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
>     base_directory = './mixnet_weights_bn'  # directory containing the ckpt
>     if not osp.exists(base_directory):
>         raise AssertionError('Checkpoint {} does not exist'.format(
>                              base_directory))
>     frozen_model = 'mixnet.pb'
>     frozen_model = osp.join(base_directory, frozen_model)
>     out_names = ['logits']
>     method = 'tfi'  # change method to 'tf' to use function _simple_run_and_freeze
>     if method == 'tf':
>         # define a TF graph: input -> MixNet -> output
>         graph = tf.Graph()
>         with graph.as_default() as g:
>             inputs = tf.placeholder(tf.float32,
>                                     shape=[BATCH_SIZE, DIM1, DIM2, 3],
>                                     name='X')
>             logits, _ = build_model(inputs, 'mixnet-s', False)
> 
>         output_name = logits.op.name
>         X = np.random.randn(BATCH_SIZE, DIM1, DIM2, 3)
>         frozen_model_file = 'mixnet_s_graph.pb'
>         coreml_model_path = 'mixnet_s_graph.mlmodel'
>         out = _simple_run_and_freeze(graph,
>                                      output_name,
>                                      frozen_model_file,
>                                      feed_dict={'X:0': X})
>     else:
>         # Freeze graph
>         _freeze_graph(base_directory, out_names, frozen_model)
>     if not osp.isfile(frozen_model):
>         raise AssertionError('Graph {} could not be frozen.'.format(
>                              frozen_model))
>     ml_model = 'mixnet_coreml.mlmodel'
>     ml_model = osp.join(base_directory, ml_model)
>     # Convert to Core ML
>     convert(frozen_model, ml_model)
>     if not osp.isfile(ml_model):
>         raise AssertionError('Core ML model {} not found.'.format(ml_model))
> ```
> 
> In a different attempt, I converted the model in an Ubuntu 16.04 machine and tried loading the `.mlmodel` file in macOS. Thereafter, I got the error mentioned in issue #336
> 
> I'm guessing the cause of the Segmentation Fault is because a node is missing from the converted graph.
> 
> Please help me out and let me know in case you need any further information. Thanks!

Hi @dhananjaisharma10, thanks for reporting this issue! I'm trying to reproduce your issue, but got following *TensorFlow* exception while running your script above:

```
Traceback (most recent call last):
  File "tmp.py", line 154, in <module>
    convert(frozen_model, ml_model)
  File "tmp.py", line 104, in convert
    add_custom_layers=True)
  File "/Volumes/data/venv-py36/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 715, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/Volumes/data/venv-py36/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 327, in _convert_pb_to_mlmodel
    tensors_evaluated = sess.run(tensors, feed_dict=input_feed_dict)
  File "/Volumes/data/venv-py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/Volumes/data/venv-py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Volumes/data/venv-py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/Volumes/data/venv-py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: Node 'mixnet-s/mixnet_model/stem/batch_normalization/FusedBatchNormV3' (type: 'Add', num of outputs: 1) does not have output 5
```

Is this expected? Also, is this a dup of https://github.com/tf-coreml/tf-coreml/issues/336 or is it seperate issues? Anyway, it'd be awesome if you can provide us a detailed reproduce steps. You can either reply in issues or [file a bug](https://github.com/tf-coreml/tf-coreml/issues/new?assignees=&labels=bug&template=--bug-report.md&title=). Thanks!

**Comment by dhananjaisharma10** [comment]
Hi

> Hi @dhananjaisharma10, thanks for reporting this issue! I'm trying to reproduce your issue, but got following _TensorFlow_ exception while running your script above:
> 
> ```
> Traceback (most recent call last):
>   File "tmp.py", line 154, in <module>
>     convert(frozen_model, ml_model)
>   File "tmp.py", line 104, in convert
>     add_custom_layers=True)
>   File "/Volumes/data/venv-py36/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 715, in convert
>     custom_conversion_functions=custom_conversion_functions)
>   File "/Volumes/data/venv-py36/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 327, in _convert_pb_to_mlmodel
>     tensors_evaluated = sess.run(tensors, feed_dict=input_feed_dict)
>   File "/Volumes/data/venv-py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
>     run_metadata_ptr)
>   File "/Volumes/data/venv-py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/Volumes/data/venv-py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
>     run_metadata)
>   File "/Volumes/data/venv-py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.OutOfRangeError: Node 'mixnet-s/mixnet_model/stem/batch_normalization/FusedBatchNormV3' (type: 'Add', num of outputs: 1) does not have output 5
> ```
> 
> Is this expected? Also, is this a dup of #336 or is it separate issues? Anyway, it'd be awesome if you can provide us a detailed reproduce steps. You can either reply in issues or [file a bug](https://github.com/tf-coreml/tf-coreml/issues/new?assignees=&labels=bug&template=--bug-report.md&title=). Thanks!

Hi! Thanks for getting back.

I get the same error if I use the pretrained weights available on the TF Mixnet page. To get around this, I trained Mixnet on a random normal distribution and then saved the checkpoints. My previous posts are with reference to these checkpoints and not the pretrained weights. Attached below is the script that I used for dummy training.

[train.py.zip](https://github.com/tf-coreml/tf-coreml/files/3774250/train.py.zip)

Yes, this issue is related to #336. The converted `.mlmodel` was throwing a Segfault, so I posted here.

Please let me know in case you need further information. Looking forward to hearing back from you.
