### ISSUE TITLE
NotImplementedError: Unsupported Ops of type: FusedBatchNormV3

### ISSUE THREAD

**Issue by panyongfeng** [tf-coreml/tf-coreml#318]
Dears,
Is there any plan to add this support?
Or 
What should I do to work around this?
thanks a lot.
Here is the log when I am translate openseq2seq pb to coreml:
...
Graph Loaded.
Now finding ops in the TF graph that can be dropped for inference
Collecting all the 'Const' ops from the graph, by running it....
Done.
Traceback (most recent call last):
  File "pb_to_coreml.py", line 7, in <module>
    input_name_shape_dict = {'ForwardPass/w2l_encoder/conv11/conv1d/ExpandDims:0' : [1, 1, 256, 64]}
  File "/Users/panyongfeng/anaconda3/lib/python3.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 621, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/Users/panyongfeng/anaconda3/lib/python3.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 294, in _convert_pb_to_mlmodel
    _check_unsupported_ops(OPS, output_feature_names, effectively_constant_ops + unused_ops)
  File "/Users/panyongfeng/anaconda3/lib/python3.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 123, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported Ops of type: FusedBatchNormV3

**Comment by 1duo** [comment]
Hi @panyongfeng, thanks for reporting this issue! It'd be great if you can share the `model.pb` and convert scripts to reproduce this issue. Thanks!

**Comment by Mstronach** [comment]
Hi @panyongfeng, this op has been added in the latest release. Please try it out and feel free to reopen this or submit a new issue if you are still experiencing issues. Thanks!
