### ISSUE TITLE
Unsupported Ops of type: SplitV

### ISSUE THREAD

**Issue by nseidl** [tf-coreml/tf-coreml#323]
Relevant information from `pip freeze`:
```
coremltools==3.0b3
tensorflow==1.12.0
tfcoreml==0.4.0b1
```

Script used:

```python
import tfcoreml as tf_converter

tf_graph_path = '/wayfair/home/ns242e/od_133/tiny/tiny-v1/train-v1_best.pb'
coreml_graph_path = tf_graph_path.replace('.pb', '.mlmodel')

coreml_model = tf_converter.convert(
    tf_model_path=tf_graph_path,
    mlmodel_path=coreml_graph_path,
    output_feature_names=['output_boxes:0'],
    input_name_shape_dict={'inputs:0': [1, 416, 416, 3]},
)
```

Script output:

```bash
Loading the TF graph...
2019-07-25 14:03:50.019583: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F
Graph Loaded.
Now finding ops in the TF graph that can be dropped for inference
Collecting all the 'Const' ops from the graph, by running it....
Done.
Traceback (most recent call last):
  File "/wayfair/home/ns242e/repos/od-yolo/translation/tensorflow_to_coreml.py", line 18, in <module>
    input_name_shape_dict={'inputs:0': [1, 416, 416, 3]},
  File "/wayfair/home/ns242e/repos/od-yolo/venv/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 621, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/wayfair/home/ns242e/repos/od-yolo/venv/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 294, in _convert_pb_to_mlmodel
    _check_unsupported_ops(OPS, output_feature_names, effectively_constant_ops + unused_ops)
  File "/wayfair/home/ns242e/repos/od-yolo/venv/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 123, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported Ops of type: SplitV
```

You can find the frozen graph used [here](https://drive.google.com/open?id=1Bgj9h6TJLwedtrhnritRs9eYm_iczG4v).

I understand that `SplitV` is not explicitly converted, but could the `SplitV` operation in the graph be converted to a `Split` operation, which is supported?

**Comment by 1duo** [comment]
This issue should be resolved with the latest coremltools. Close due to inactivity. Feel free to re-open if you still see the issue. Thanks!

**Comment by fellowProgrammer** [comment]
I am getting this error.
I am using `coremltools==3.2` and `tfcoreml==1.1`.

This is my conversion script:

```
frozen_model_file = os.path.abspath('frozen_darknet_yolov3_model.pb')
input_tensor_shapes = {"inputs:0": [1, 416, 416, 3]}
# Output CoreML model path
coreml_model_file = './model.mlmodel'
output_tensor_names = ['output_boxes:0']
def convert():
    # Read the pb model
    with tf.gfile.GFile(frozen_model_file, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    # Then, we import the graph_def into a new Graph
    tf.import_graph_def(graph_def, name="")
    # Convert
    tfcoreml.convert(
        tf_model_path=frozen_model_file,
        mlmodel_path=coreml_model_file,
        input_name_shape_dict=input_tensor_shapes,
        output_feature_names=output_tensor_names)
convert()
```

This is the error I get:

```
Graph Loaded.
Now finding ops in the TF graph that can be dropped for inference
Collecting all the 'Const' ops from the graph, by running it....
Done.
Traceback (most recent call last):
  File "convertToCoreML.py", line 42, in <module>
    convert()
  File "convertToCoreML.py", line 41, in convert
    output_feature_names=output_tensor_names)
  File "/content/drive/My Drive/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 718, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/content/drive/My Drive/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 359, in _convert_pb_to_mlmodel
    _check_unsupported_ops(OPS, output_feature_names, effectively_constant_ops + unused_ops)
  File "/content/drive/My Drive/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 188, in _check_unsupported_ops
    ','.join(unsupported_op_types)))
NotImplementedError: Unsupported Ops of type: SplitV
```

I am trying to convert my .pb model to a coreml model. I determined the input and out names using the inspect_pb.py script provided.

**Comment by 1duo** [comment]
@fellowProgrammer Can you providing `minimum_ios_deployment_target='13'` in your convert call. This op is provided in iOS 13 or later.

**Comment by fellowProgrammer** [comment]
I added that I am now getting another error:

`ValueError: Incompatible dimension 3 in Sub operation detector/darknet-53/Conv/BatchNorm/FusedBatchNorm/Sub`
