### ISSUE TITLE
"Type 20 cannot be mapped" and RecursionError

### ISSUE THREAD

**Issue by b-onc** [tf-coreml/tf-coreml#324]
Hello!

using 
coremltools 3.0b3
tfcoreml 0.4.0b1

When I try to convert my model (`.pb`) with `use_coreml_3 = True`, I get 
```
Type 20 cannot be mapped
Type 20 cannot be mapped
Traceback (most recent call last):
  File "/anaconda3/envs/coreml/lib/python3.7/site-packages/coremltools/converters/nnssa/frontend/tensorflow/graph_pass/delete_asserts.py", line 22, in all_assert_leaves
    memo[nodename] = all(all_assert_leaves(gdict, o, memo) for o in gdict[nodename].outputs)
  File "/anaconda3/envs/coreml/lib/python3.7/site-packages/coremltools/converters/nnssa/frontend/tensorflow/graph_pass/delete_asserts.py", line 22, in <genexpr>
    memo[nodename] = all(all_assert_leaves(gdict, o, memo) for o in gdict[nodename].outputs)
... <and lots of these, repeating>
RecursionError: maximum recursion depth exceeded
```
Our graph has cycles that we know of, so shouldn't it raise `ValueError: Graph has cycles`?

Regards

**Comment by b-onc** [comment]
We've found that running the converter with `use_coreml_3 = False` gives the correct output, and also found the underlying error: the recursion limit of 2000 wasn't enough for our huge model, 4000 works.
Also Type 20 is `DT_RESOURCE`
