### ISSUE TITLE
TypeError: Shape Translator missing for OP of type GatherV2

### ISSUE THREAD

**Issue by kezakool** [tf-coreml/tf-coreml#329]
Hello there,

First, thanks you for all your work, you're the tiny bound between google and Apple! :)

I'm working on a tensorflow project 1.13, in speech reco, and i'm struggling to deploy it on IOS, with two errors : 
- Occurring on the stft in the features preprocessing steps of my graph -> TypeError: Shape Translator missing for OP of type GatherV2.
    -> I feel like its more a feature request, but if you have a workaround, I'll be glad to take it
- Occurring on my LSTM layer (tried 2 differents ways , first a tf.nn.dynamic_rnn then a keras LSTM layer mixed in my tf graph) -> Graph as cycles error
    -> my next try is to rebuild all the subgraph with keras and trying keras_convert, anything easier is welcome

If i missed something, please tell me :)

many thanks

**Comment by kezakool** [comment]
is there someone here that can help? thanks

**Comment by kezakool** [comment]
Hi @1duo , thanks for helping! 

you'll find here a shared notebook : https://colab.research.google.com/drive/1cZxfNWIlL4U856wTb5z6CzkdDYpZt9De

and here are the two frozen model : https://we.tl/t-mrDG2HotZo

- frozen_model.pb : give me this error 
/usr/local/lib/python3.6/dist-packages/tfcoreml/_tf_graph_transform.py in _push_stack(stack, node, in_stack)
     36   stack.append(node)
     37   if node in in_stack:
---> 38     raise ValueError('Graph has cycles.')
     39   else:
     40     in_stack[node] = True

ValueError: Graph has cycles.

- basiclstm_frozen_model.pb : give me this error 
/usr/local/lib/python3.6/dist-packages/tfcoreml/_interpret_shapes.py in _get_translator_function(op_name)
     12     return _SHAPE_TRANSLATOR_REGISTRY[op_name]
     13   else:
---> 14     raise TypeError("Shape Translator missing for OP of type %s." % (op_name))
     15 
     16 def _labeled_dims_to_rank_4_shape(blob_name, context):

TypeError: Shape Translator missing for OP of type GatherV2.

Thanks

**Comment by kezakool** [comment]
Hi @1duo, i used the same exact as you said, and unfortunately i get the result i gave you

**Comment by 1duo** [comment]
Hi @kezakool, forgot to mention you’ll need to use use_coreml_4=True flag when calling convert(). You’ll see these error gone if you do that. However, this model contains beam search decoder currently we currently still working on.

**Comment by kezakool** [comment]
Hi @1duo, thanks, i did that, and i got a new error.. it means we re improving! but i feel there is still many things to do (i can pull out the beamsearchdecoder if needed)

Here is the error description : 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 73, in visit
    ret = visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 952, in visit_Reshape
    np.reshape(self.gdict[node.inputs[0]].attr['symbolic_value'].val, shape)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 292, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

Unable to infer type of node audio_to_spectrogram/linear_to_mel_weight_matrix/frame/Reshape_1 (Reshape)
Unable to infer type of node audio_to_spectrogram/linear_to_mel_weight_matrix/frame/GatherV2 (Gather)
Unable to infer type of node audio_to_spectrogram/linear_to_mel_weight_matrix/frame/Reshape_4 (Reshape)
Failed to infer type of audio_to_spectrogram/linear_to_mel_weight_matrix/frame/Reshape_1:Reshape
'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 73, in visit
    ret = visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 952, in visit_Reshape
    np.reshape(self.gdict[node.inputs[0]].attr['symbolic_value'].val, shape)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 292, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

Unable to infer type of node audio_to_spectrogram/linear_to_mel_weight_matrix/frame/Reshape_1 (Reshape)
Unable to infer type of node audio_to_spectrogram/linear_to_mel_weight_matrix/frame/GatherV2 (Gather)
Unable to infer type of node audio_to_spectrogram/linear_to_mel_weight_matrix/frame/Reshape_4 (Reshape)
Op ComplexAbs Not implemented
Op ComplexAbs Not implemented
Failed to infer type of audio_to_spectrogram/Tensordot/transpose:Transpose

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 73, in visit
    ret = visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1801, in visit_Transpose
    assert (builtins.is_tensor(inputtype))
AssertionError

Unable to infer type of node audio_to_spectrogram/Tensordot/transpose (Transpose)
Op ComplexAbs Not implemented
Failed to infer type of audio_to_spectrogram/Tensordot/transpose:Transpose

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 73, in visit
    ret = visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1801, in visit_Transpose
    assert (builtins.is_tensor(inputtype))
AssertionError

Unable to infer type of node audio_to_spectrogram/Tensordot/transpose (Transpose)
Unable to infer type of node audio_to_spectrogram/Tensordot/Reshape (Reshape)
Op ComplexAbs Not implemented
Failed to infer type of audio_to_spectrogram/Tensordot/transpose:Transpose

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 73, in visit
    ret = visitor(node)
  File "/usr/local/lib/python3.6/dist-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1801, in visit_Transpose
    assert (builtins.is_tensor(inputtype))
AssertionError

Unable to infer type of node audio_to_spectrogram/Tensordot/transpose (Transpose)
Unable to infer type of node audio_to_spectrogram/Tensordot/Reshape (Reshape)
30 nodes deleted
0 nodes deleted
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-7-39a3ab7e97b5> in <module>()
      8 frozen_coremlmodel=os.path.join("basiclstm_frozen_model.mlmodel")
      9 
---> 10 coremlmodel = tfcoreml.convert(tf_model_path=frozen_output_graph, mlmodel_path=frozen_coremlmodel,output_feature_names=coreml_output,input_name_shape_dict={input_node: input_shape},use_coreml_3=True)
     11 
     12 coreml_model.save(frozen_coremlmodel)

2 frames
/usr/local/lib/python3.6/dist-packages/coremltools/converters/nnssa/frontend/tensorflow/load.py in load(tfgraph, resume_on_errors, **kwargs)
     70         for f in ssa.functions.values():
     71             for n in f.graph.values():
---> 72                 assert (n.datatype is not None)
     73     return ssa

AssertionError:

**Comment by 1duo** [comment]
Hi @kezakool, thanks for trying the new flag, locally I'm getting different errors. Did you already tried to pull out the beam search part? If so, could you share the modified model? Thanks!
