### ISSUE TITLE
Converter: TF graph parsing fails with target_ios=13

### ISSUE THREAD

**Issue by lukereichold** [tf-coreml/tf-coreml#353]
## 🐞Describe the bug
I have frozen my TF model as `frozen_model.pb`. It appears fully formed and valid and is inspectable via the [tf-coreml inspect script](https://github.com/tf-coreml/tf-coreml/blob/master/utils/inspect_mlmodel.py). The converter script runs successfully when I do **not** specify a `target_ios` version (defaulting to '12'). ✓

However, I would like to support input tensors of rank 5 so I passed `target_ios='13'` as an argument to `tf_converter.convert(..)` and I receive the following error trace as the script tries to parse the TF graph. Specifying the new `target_ios` version is the ONLY change made.

## Trace
```python
/root/venv3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Type 8 cannot be mapped
Type 8 cannot be mapped
Type 8 cannot be mapped
Type 8 cannot be mapped
Type 8 cannot be mapped
Type 8 cannot be mapped
Traceback (most recent call last):
  File "coreML_converter.py", line 10, in <module>
    'Placeholder': [1, 248, 224, 224, 3]
  File "/root/venv3/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 688, in convert
    custom_shape_functions=custom_shape_functions)
  File "/root/venv3/lib/python3.6/site-packages/coremltools/converters/tensorflow/_tf_converter.py", line 42, in convert
    ssa = frontend_load(filename, resume_on_errors=False, inputs=inputs, outputs=outputs, **kwargs)
  File "/root/venv3/lib/python3.6/site-packages/coremltools/converters/nnssa/frontend/tensorflow/load.py", line 40, in load
    ssa = graphdef_to_ssa(gd)
  File "/root/venv3/lib/python3.6/site-packages/coremltools/converters/nnssa/frontend/tensorflow/graphdef_to_ssa.py", line 44, in graphdef_to_ssa
    gd = graphdef_to_dict(gdorig)
  File "/root/venv3/lib/python3.6/site-packages/coremltools/converters/nnssa/frontend/tensorflow/parse.py", line 141, in graphdef_to_dict
    ret[node.name] = ParsedTFNode(node)
  File "/root/venv3/lib/python3.6/site-packages/coremltools/converters/nnssa/frontend/tensorflow/parsed_tf_node.py", line 36, in __init__
    self.attr = {k: parse_attr(v) for k, v in tfnode.attr.items()}
  File "/root/venv3/lib/python3.6/site-packages/coremltools/converters/nnssa/frontend/tensorflow/parsed_tf_node.py", line 36, in <dictcomp>
    self.attr = {k: parse_attr(v) for k, v in tfnode.attr.items()}
  File "/root/venv3/lib/python3.6/site-packages/coremltools/converters/nnssa/frontend/tensorflow/parse.py", line 129, in parse_attr
    return parse_tensor(attr.tensor)
  File "/root/venv3/lib/python3.6/site-packages/coremltools/converters/nnssa/frontend/tensorflow/parse.py", line 71, in parse_tensor
    retobj = typ()
TypeError: 'NoneType' object is not callable
```

## To Reproduce
- If a python script can reproduce the error, please paste the code snippet
```python
import tfcoreml as tf_converter

tf_converter.convert(tf_model_path='src/frozen-export/frozen_network.pb',
                     mlmodel_path='model.mlmodel',
                     target_ios='13',
                     add_custom_layers=True,
                     output_feature_names=['PadV2', 'PadV2_1'],
                     input_name_shape_dict={
                         'Placeholder_1': [1, 173774, 2],
                         'Placeholder': [1, 248, 224, 224, 3]
                     })

```
- If applicable, please attach tensorflow model
- Model inspection: 
[model_inspect.txt](https://github.com/tf-coreml/tf-coreml/files/3795502/model_inspect.txt)

- If model conversion succeeds, however, there is numerical mismatch between the original and the coreml model, please paste python script used for comparison (tf code etc.)

## System environment (please complete the following information):
 - coremltools version  (e.g., 3.0b5): `coremltools (3.0)`
 - tf-coreml version (e.g. 0.4.0b1): `tfcoreml (1.0)`
 - tensorflow version (e.g. 1.14): `1.14.0`
 - OS (e.g., MacOS, Linux):  `Ubuntu 18.04.3 (LTS) x64`
 - macOS version (if applicable): 
 - How you install python (anaconda, virtualenv, system): `virtualenv`
 - python version: `Python 3.6.8`
 - any other relevant information:

Thanks!

**Comment by 1duo** [comment]
Hi @lukereichold, thanks for reporting this issue! The `target_ios` flag has a kind of misleading name and we have rename it as `minimum_ios_deployment_target`. In your case, the model converted (with default option) should be able to executed on both iOS 12, iOS 13 and later in the future. So you should be unblocked for now. 

On the other hand, it'd be great if you can post a link to the model for us to investigate issues on iOS 13 conversion path. Thanks!

**Comment by lukereichold** [comment]
Hi @1duo, thanks for the response. Using the default iOS 12 (and the latest versions of `tfcoreml` and `coremltools`), the converter call is able to pass the parsing phase but the conversion fails. 

```bash
"Shape Translator missing for OP of type Abs."
"Shape Translator missing for OP of type StridedSlide." 
```

With `minimum_ios_deployment_target='13'`, the script fails earlier in the parsing of the actual graph (before attempting to convert). Ideally I would like to use deployment target of 13 because I suspect that even once fixing the incompatible ops with the above `minimum_ios_deployment_target='12'`, I will require iOS 13 due to my model having tensors of rank 5. (See my `input_name_shape_dict` values in the above sample code. Is that a correct assumption?

[Here is a link to the frozen TF model](https://drive.google.com/file/d/1NZWhM1JkAXIAjjd_BwBhyqLVwO-Jfv2l/view?usp=sharing).
