### ISSUE TITLE
OP Transpose support or not

### ISSUE THREAD

**Issue by wanghuijing** [tf-coreml/tf-coreml#358]
HELLO:

I try to translate my pb models.Here is the error.

37/1030: Analysing op name: heatmap_regression/bneck_heatmaps/se_block_9/dense_15/Tensordot/concat ( type:  ConcatV2 )
Traceback (most recent call last):
  File "convertor.py", line 5, in <module>
    input_name_shape_dict={'input:0': [1, 224, 224, 3]})
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 718, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 411, in _convert_pb_to_mlmodel
    convert_ops_to_layers(context)
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_ops_to_layers.py", line 186, in convert_ops_to_layers
    translator(op, context)
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_layers.py", line 119, in concat
    ss_layers._add_concat(op, context)
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_shape_sensitive_layers.py", line 109, in _add_concat
    make_tensor(input, context)
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_layers_common.py", line 46, in make_tensor
    add_const(context, x.name, context.consts[x.name], x.name)
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_layers_common.py", line 26, in add_const
    _add_const(context, name, x, output_name, shape)
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_shape_sensitive_layers.py", line 25, in _add_const
    status = interpret_shape(output_name, context)
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_interpret_shapes.py", line 267, in _interpret_shape
    return _interpret_and_label_shapes(blob_name, context, tracking_dict={})
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_interpret_shapes.py", line 236, in _interpret_and_label_shapes
    status = _interpret_and_label_shapes(output_name, context, tracking_dict)
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_interpret_shapes.py", line 241, in _interpret_and_label_shapes
    fun = _get_translator_function(op.type)
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_interpret_shapes.py", line 14, in _get_translator_function
    raise TypeError("Shape Translator missing for OP of type %s." % (op_name))
TypeError: Shape Translator missing for OP of type Transpose.

And I notice in _interpret_shapes.py.

# TODO. Need to figure out the correct rule for adding these ops:
# Slice, StridedSlice, ExtractImagePatches, ArgMax, Shape,
# Transpose, Prod, Max, Min, MatMul, OneHot, Gather, FloorMod,

If Transpose is support?If yes,can tell me how ti use it?
Thanks!

**Comment by 1duo** [comment]
@wanghuijing Thanks for reporting this issue! Try convert your model using specification 4 by set `minimum_ios_deployment_target='13'` in your `convert()` call.

**Comment by wanghuijing** [comment]
Thank you for the answer.I did this.
1.tf_converter.convert(tf_model_path = 'frozen_model.pb',
                     mlmodel_path = 'frozen_model.mlmodel',
                     output_feature_names = ['conf_reg:0'],
                     input_name_shape_dict={'input:0': [1, 224, 224, 3]},
		     minimum_ios_deployment_target='13')

return :

/home/whj/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "convertor.py", line 6, in <module>
    minimum_ios_deployment_target='13')
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 673, in convert
    check_input_output_names(input_name_shape_dict, output_feature_names)
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 79, in check_input_output_names
    'Recommendation: \n {} {}'.format(input_string, output_string))
ValueError: with target deployment > '12', the converter drops ':' convention for input and output. Please provide input and output without ':' e.g. `input` instead of `input:0`
Recommendation: 
 Input: ['input'] instead of ['input:0']
 Output: ['conf_reg'] instead of ['conf_reg:0']

 BUT:pb info is 
name = import/input:0 : (?, 224, 224, 3)
@output shapes:
name = import/conf_reg:0 : (?, 7, 7, 3)


2.tf_converter.convert(tf_model_path = 'frozen_model_head.pb',
                     mlmodel_path = 'frozen_model.mlmodel',
                     output_feature_names = ['conf_reg'],
                     input_name_shape_dict={'input': [1, 224, 224, 3]},
		     minimum_ios_deployment_target='13')

return:
  File "/home/whj/.local/lib/python3.5/site-packages/coremltools/converters/nnssa/commons/builtins/__init__.py", line 11, in <module>
    from .type_tensor import tensor, is_tensor_and_is_compatible, \
  File "/home/whj/.local/lib/python3.5/site-packages/coremltools/converters/nnssa/commons/builtins/type_tensor.py", line 10, in <module>
    import sympy as sm
ImportError: No module named 'sympy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "convertor.py", line 6, in <module>
    minimum_ios_deployment_target='13')
  File "/home/whj/AI/ios/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 691, in convert
    custom_shape_functions=custom_shape_functions)
  File "/home/whj/.local/lib/python3.5/site-packages/coremltools/converters/tensorflow/_tf_converter.py", line 71, in convert
    raise ImportError('frontend converter not found. {}'.format(e))
ImportError: frontend converter not found. No module named 'sympy'




Look forward your reply.

**Comment by wanghuijing** [comment]
I inatall sympy .It works.

**Comment by wanghuijing** [comment]
It works!Thanks o lot.

**Comment by wanghuijing** [comment]
It works.Thanks a lot.

**Comment by 1duo** [comment]
👍
