### ISSUE TITLE
Support for StridedSlice ? 

### ISSUE THREAD

**Issue by dimitriGallos** [tf-coreml/tf-coreml#364]
## 🐞Describe the bug
A clear and brief description of what the bug is.

I am trying to convert my tensorflow 2.0 model to coreml. My saved model is in checkpoint format so i do the following to create a SavedModel:

```
model = get_model()
checkpoint = tf.train.Checkpoint(model=model)
checkpoint_manager = tf.train.CheckpointManager(checkpoint, checkpoint_dir, None)
checkpoint.restore(checkpoint_manager.checkpoints[relative_snapshot_id])
tf.saved_model.save(checkpoint.model, save_dir)
```

Following that, I set inputs and outputs and I call the  following:

```
model = tfcoreml.convert(save_dir,
                         mlmodel_path='./model.mlmodel',
                         input_name_shape_dict=input_name_shape_dict,
                         output_feature_names=[OUTPUT_LAYER_NAME],
                         minimum_ios_deployment_target='13')
model.save('IKModel3.mlmodel')
```

## Trace
 File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 978, in visit_Reshape
    left_volume = left_volume * i
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/flatten/Reshape" (Reshape)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Reshape" (Reshape)
unsupported operand type(s) for *: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 978, in visit_Reshape
    left_volume = left_volume * i
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Reshape" (Reshape)
[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/Identity" (Identity)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/flatten/Reshape" (Reshape)
unsupported operand type(s) for *: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 978, in visit_Reshape
    left_volume = left_volume * i
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/flatten/Reshape" (Reshape)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Reshape" (Reshape)
unsupported operand type(s) for *: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 978, in visit_Reshape
    left_volume = left_volume * i
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Reshape" (Reshape)
[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/Identity" (Identity)
[TypeInference] Unable to infer type of node "Func/model_1/StatefulPartitionedCall/StatefulPartitionedCall/output/_117" (Identity)
[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/Identity" (Identity)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Shape" (Shape)
unorderable types: NoneType() > int()
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1094, in visit_Shape
    if len(shape) > 0 and all([dim > 0 for dim in shape]):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1094, in <listcomp>
    if len(shape) > 0 and all([dim > 0 for dim in shape]):
TypeError: unorderable types: NoneType() > int()

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Shape" (Shape)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Reshape" (Reshape)
unsupported operand type(s) for *: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 978, in visit_Reshape
    left_volume = left_volume * i
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Reshape" (Reshape)
[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/Identity" (Identity)
[TypeInference] Unable to infer type of node "Func/model_1/StatefulPartitionedCall/StatefulPartitionedCall/output/_117" (Identity)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Shape" (Shape)
unorderable types: NoneType() > int()
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1094, in visit_Shape
    if len(shape) > 0 and all([dim > 0 for dim in shape]):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1094, in <listcomp>
    if len(shape) > 0 and all([dim > 0 for dim in shape]):
TypeError: unorderable types: NoneType() > int()

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Shape" (Shape)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Shape" (Shape)
unorderable types: NoneType() > int()
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1094, in visit_Shape
    if len(shape) > 0 and all([dim > 0 for dim in shape]):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1094, in <listcomp>
    if len(shape) > 0 and all([dim > 0 for dim in shape]):
TypeError: unorderable types: NoneType() > int()

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Shape" (Shape)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/strided_slice" (StridedSlice)
'NoneType' object has no attribute 'get_shape'
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1405, in visit_StridedSlice
    input_shape = input_type.get_shape()
AttributeError: 'NoneType' object has no attribute 'get_shape'

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/strided_slice" (StridedSlice)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Reshape" (Reshape)
unsupported operand type(s) for *: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 978, in visit_Reshape
    left_volume = left_volume * i
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Reshape" (Reshape)
[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/Identity" (Identity)
[TypeInference] Unable to infer type of node "Func/model_1/StatefulPartitionedCall/StatefulPartitionedCall/output/_117" (Identity)
[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/Identity" (Identity)
[TypeInference] Unable to infer type of node "Func/model_1/StatefulPartitionedCall/output/_57" (Identity)
[TypeInference] Unable to infer type of node "Identity" (Identity)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Reshape" (Reshape)
unsupported operand type(s) for *: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 978, in visit_Reshape
    left_volume = left_volume * i
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Reshape" (Reshape)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Reshape" (Reshape)
unsupported operand type(s) for *: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 978, in visit_Reshape
    left_volume = left_volume * i
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Reshape" (Reshape)
[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/Identity" (Identity)
[TypeInference] Unable to infer type of node "Func/model_1/StatefulPartitionedCall/StatefulPartitionedCall/output/_117" (Identity)
[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/Identity" (Identity)
[TypeInference] Unable to infer type of node "Func/model_1/StatefulPartitionedCall/output/_57" (Identity)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Shape" (Shape)
unorderable types: NoneType() > int()
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1094, in visit_Shape
    if len(shape) > 0 and all([dim > 0 for dim in shape]):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1094, in <listcomp>
    if len(shape) > 0 and all([dim > 0 for dim in shape]):
TypeError: unorderable types: NoneType() > int()

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Shape" (Shape)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Shape" (Shape)
unorderable types: NoneType() > int()
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1094, in visit_Shape
    if len(shape) > 0 and all([dim > 0 for dim in shape]):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1094, in <listcomp>
    if len(shape) > 0 and all([dim > 0 for dim in shape]):
TypeError: unorderable types: NoneType() > int()

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/Shape" (Shape)
[TypeInference] Failed to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/strided_slice" (StridedSlice)
'NoneType' object has no attribute 'get_shape'
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 86, in visit
    ret = visitor(node)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 1405, in visit_StridedSlice
    input_shape = input_type.get_shape()
AttributeError: 'NoneType' object has no attribute 'get_shape'

[TypeInference] Unable to infer type of node "model_1/StatefulPartitionedCall/StatefulPartitionedCall/reshape/strided_slice" (StridedSlice)
Traceback (most recent call last):
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/tensorflow/_tf_converter.py", line 69, in convert
    ssa = frontend_load(filename, resume_on_errors=False, inputs=inputs, outputs=outputs, **kwargs)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/tensorflow/load.py", line 76, in load
    common_pass(ssa, resume_on_errors)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/common_pass.py", line 27, in common_pass
    p(ssa)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 2191, in type_inference_pass
    graph_replace_symbolic_values(nnssa.functions[i].graph)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 2175, in graph_replace_symbolic_values
    v.datatype = recursive_replace_symbols_in_type_with_unknown(v.datatype)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 2144, in recursive_replace_symbols_in_type_with_unknown
    tuple(-1 if issubclass(type(t), sm.Basic) else int(t) for t in dtype.get_shape()))
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/nnssa/frontend/graph_pass/type_inference.py", line 2144, in <genexpr>
    tuple(-1 if issubclass(type(t), sm.Basic) else int(t) for t in dtype.get_shape()))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "convertFromTFToCoreML.py", line 81, in <module>
    minimum_ios_deployment_target='13')
  File "/project_dir/env/lib/python3.5/site-packages/tfcoreml/_tf_coreml_converter.py", line 691, in convert
    custom_shape_functions=custom_shape_functions)
  File "/project_dir/env/lib/python3.5/site-packages/coremltools/converters/tensorflow/_tf_converter.py", line 73, in convert
    raise RuntimeError('failed to convert from TensorFlow to IR. {}'.format(e))
RuntimeError: failed to convert from TensorFlow to IR. int() argument must be a string, a bytes-like object or a number, not 'NoneType'

## System environment (please complete the following information):
 - coremltools version 3.1
 - tf-coreml version 1,1 
 - tensorflow version 2.0
 - Ubuntu 16.04
 - python version 3.5

**Comment by Queequeg92** [comment]
Any updates? When tf-coreml throws some errors, I'm very confused whether these ops are not supported by tf-coreml or by coremltools. Only part of ops supported by coremltools are supported by tf-coreml, is that true?
