### ISSUE TITLE
Problem converting savedModel

### ISSUE THREAD

**Issue by flocked** [tf-coreml/tf-coreml#368]
## 🐞Describe the bug
I have this savedModel including weights which got generated by tf.estimator.Estimator export_saved.model in Tensorflow 1.14. It contains:

> saved_model.pb
> variables/variables.data-00000-of-00001
> variables/variables.index

[Link to dropbox because of its 70mb size.](https://www.dropbox.com/s/kinfmdxlzw4epn3/1576085619.zip?dl=0)

Trying to convert it with tf-coreml doesn't work. Here is the code I used for this specific model:

```
import tensorflow as tf
import tfcoreml

input_tensor_shapes = {"Placeholder": ( -1, 2 ) }
tf_model_path = 'PATH_TO_SAVEDMODEL_DICTONARY'
coreml_model_file = '/Users/USERNAME/Downloads/freeze.mlmodel'
output_tensor_names = ['strided_slice_13', 'strided_slice_23']

coreml_model = tfcoreml.convert (
tf_model_path=tf_model_path,
mlmodel_path=coreml_model_file,
input_name_shape_dict=input_tensor_shapes,
output_feature_names=output_tensor_names, minimum_ios_deployment_target='13')
```
 Following error:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/florianzand/Downloads/Convert Kopie.py", line 22, in <module>
    output_feature_names=output_tensor_names, minimum_ios_deployment_target='13')
  File "/usr/local/lib/python3.7/site-packages/tfcoreml/_tf_coreml_converter.py", line 691, in convert
    custom_shape_functions=custom_shape_functions)
  File "/usr/local/lib/python3.7/site-packages/coremltools/converters/tensorflow/_tf_converter.py", line 59, in convert
    filename = _graph_def_from_saved_model_or_keras_model(filename)
  File "/usr/local/lib/python3.7/site-packages/coremltools/converters/tensorflow/_tf_converter.py", line 124, in _graph_def_from_saved_model_or_keras_model
    raise RuntimeError('Failed to load SavedModel or .h5 model. {}.'.format(e))
RuntimeError: Failed to load SavedModel or .h5 model. 'AutoTrackable' object has no attribute 'call'.
```
I then changed the code of coremltools/converts/tensorflow/_tf_converter.py
```
def _graph_def_from_saved_model_or_keras_model(filename):
(…)
	#removed following two lines and replace with the other two
    # func = _saving_utils.trace_model_call(model)
        # concrete_func = func.get_concrete_function()
        concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
        frozen_func = _convert_to_constants.convert_variables_to_constants_v2(concrete_func)
```
Which caused this error:
`NotImplementedError: numpy() is only available when eager execution is enabled.`

So I added this to my converter code:
`tf.compat.v1.enable_eager_execution()`

Which caused this problem:
```
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/convert_to_constants.py", line 479, in convert_variables_to_constants_v2
    raise ValueError("Cannot find the Placeholder op that is an input "
ValueError: Cannot find the Placeholder op that is an input to the ReadVariableOp.
```

Has anyone an idea what's going on? Are savedModels from Tensorflow 1.X exported with estimator not supported?

 - coremltools version/tf-coreml version
Newest/3.1
 - tensorflow version:
1.14
 - macOS version:
10.15.1
 - python version:
3.7

**Comment by 1duo** [comment]
Hi @flocked, SavedModel format support was added for TensorFlow 2.x+, for TensorFlow 1.x, only frozen graph (.pb) file is supported.
