### ISSUE TITLE
Op type not registered 'TFLite_Detection_PostProcess' in binary 

### ISSUE THREAD

**Issue by aminbenarieb** [tf-coreml/tf-coreml#383]
## 🐞Describe the bug
I am trying to convert tensorflow SSD MobilenetV2 model (frozen graph) to coreml model using 
tfcoreml.convert function and getting error `Op type not registered 'TFLite_Detection_PostProcess' in binary `.

## Trace
```
Traceback (most recent call last):
  File "coreml.py", line 144, in <module>
    main()
  File "/Users/aminbenarieb/.virtualenvs/coreml_1.14/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aminbenarieb/.virtualenvs/coreml_1.14/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/aminbenarieb/.virtualenvs/coreml_1.14/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aminbenarieb/.virtualenvs/coreml_1.14/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "coreml.py", line 129, in main
    mlmodel_path
  File "coreml.py", line 44, in tf_convert_to_coreml
    the_graph = load_graph(tf_model_path)
  File "coreml.py", line 62, in load_graph
    tfc.import_graph_def(original_gdef, name='')
  File "/Users/aminbenarieb/.virtualenvs/coreml_1.14/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/aminbenarieb/.virtualenvs/coreml_1.14/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 427, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'TFLite_Detection_PostProcess' in binary running on Amins-MBP.Dlink. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
```

## My Code
```
import tfcoreml
ssd_model = tfcoreml.convert(
        tf_model_path=tf_model_path,
        mlmodel_path=mlmodel_path,
        input_name_shape_dict={ input_tensor: [batchSize, input_height, input_width, channels] },
        output_feature_names=output_feature_names,
        is_bgr=is_bgr,
        class_labels=['wbc'],
        minimum_ios_deployment_target='13')
```

## System environment:
 - tf-coreml versions: 1.1, 1.0, 0.3
 - tensorflow versions: 2.1, 1.14:
 - macOS version 10.15):
 - How you install python (virtualenv):
 - python 3.7.6:

## Context
Originally I folowwed [this notebook](https://github.com/apple/coremltools/blob/master/examples/neural_network_inference/tensorflow_converter/Tensorflow_1/ssd_example.ipynb) and I've also used original https://apple.github.io/coremltools/ but got the same result.

**Comment by aminbenarieb** [comment]
I closing this issue in favour of https://github.com/apple/coremltools/issues/642.
