### ISSUE TITLE
SSDLite conversion issue [FusedBatchNormV3' (type: 'Add', num of outputs: 1) does not have output 5)]

### ISSUE THREAD

**Issue by dlawrences** [tf-coreml/tf-coreml#386]
Hi

First things first, environment config:

- tensorflow: 1.15.0
- coremltools: 3.1
- tfcoreml: 1.1
- CUDA 10.1
- cuDNN: 7.6.5.32-1

The model that I am trying to convert is based on the TensorFlow [ssdlite_mobilenet_v2_coco](http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz), retrained on 4 classes on an input of 768x768.

I have exported the graph for inference using [export_inference_graph.py](https://github.com/tensorflow/models/blob/master/research/object_detection/export_inference_graph.py).

I have also optimized the graph by removing unused nodes based on the input/output tensors.

Final error (entire stack trace is also available at the end):
```
tensorflow.python.framework.errors_impl.OutOfRangeError: Node 'FeatureExtractor/MobilenetV2/Conv/BatchNorm/FusedBatchNormV3' (type: 'Add', num of outputs: 1) does not have output 5
```
Sample script:
```
import numpy as np

import tensorflow as tf
from tensorflow.python.tools import strip_unused_lib
from tensorflow.python.framework import dtypes
from tensorflow.python.platform import gfile

import tfcoreml
import coremltools

# From where to load the saved_model.pb file.
saved_model_path = "model/saved_model"

# Where to save the final Core ML model file.
coreml_model_path = "/coreml/MobileNetV2_SSDLite.mlmodel"

# The number of predicted classes, excluding background.
num_classes = 4

# The number of predicted bounding boxes.
num_anchors = 11526

# Size of the expected input image.
input_width = 768
input_height = 768

# =============================
# PART 1: MobileNetV2 + SSDLite
# =============================

# Temporary file. You can delete this after the conversion is done.
frozen_model_file = "frozen_model.pb"

# Names of the interesting tensors in the graph. We use "Postprocessor/convert_scores"
# instead of "concat_1" because this already applies the sigmoid to the class scores.
input_node = "Preprocessor/sub"
bbox_output_node = "concat"
class_output_node = "Postprocessor/convert_scores"

input_tensor = input_node + ":0"
bbox_output_tensor = bbox_output_node + ":0"
class_output_tensor = class_output_node + ":0"


def load_saved_model(path):
    """Loads a saved model into a graph."""
    print("Loading saved_model.pb from '%s'" % path)
    the_graph = tf.Graph()
    with tf.Session(graph=the_graph) as sess:
        tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], path)
    return the_graph


def optimize_graph(graph):
    """Strips unused subgraphs and save it as another frozen TF model."""
    gdef = strip_unused_lib.strip_unused(
        input_graph_def=graph.as_graph_def(),
        input_node_names=[input_node],
        output_node_names=[bbox_output_node, class_output_node],
        placeholder_type_enum=dtypes.float32.as_datatype_enum)

    with gfile.GFile(frozen_model_file, "wb") as f:
        f.write(gdef.SerializeToString())


# Load the original graph and remove anything we don't need.
the_graph = load_saved_model(saved_model_path)
optimize_graph(the_graph)

# Convert to Core ML model.
ssd_model = tfcoreml.convert(
    tf_model_path=frozen_model_file,
    mlmodel_path=coreml_model_path,
    input_name_shape_dict={input_tensor: [1, input_height, input_width, 3]},
    image_input_names=input_tensor,
    output_feature_names=[bbox_output_tensor, class_output_tensor],
    is_bgr=False,
    red_bias=-1.0,
    green_bias=-1.0,
    blue_bias=-1.0,
    image_scale=2. / 255)
```

All stack trace:
```
C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\python.exe D:/WORK/Personal/Innaite/projects/matchpoint_ml_tf2coreml/convert-mobilenet-model-to-coreml-tfcoreml.py
WARNING:root:TensorFlow version 1.15.0 detected. Last version known to be fully compatible is 1.14.0 .
Loading saved_model.pb from 'model/saved_model'
WARNING:tensorflow:From D:/WORK/Personal/Innaite/projects/matchpoint_ml_tf2coreml/convert-mobilenet-model-to-coreml-tfcoreml.py:77: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From D:/WORK/Personal/Innaite/projects/matchpoint_ml_tf2coreml/convert-mobilenet-model-to-coreml-tfcoreml.py:77: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-03-05 14:54:53.263674: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
WARNING:tensorflow:From D:/WORK/Personal/Innaite/projects/matchpoint_ml_tf2coreml/convert-mobilenet-model-to-coreml-tfcoreml.py:78: The name tf.saved_model.tag_constants.SERVING is deprecated. Please use tf.saved_model.SERVING instead.

WARNING:tensorflow:From D:/WORK/Personal/Innaite/projects/matchpoint_ml_tf2coreml/convert-mobilenet-model-to-coreml-tfcoreml.py:78: The name tf.saved_model.tag_constants.SERVING is deprecated. Please use tf.saved_model.SERVING instead.

WARNING:tensorflow:From D:/WORK/Personal/Innaite/projects/matchpoint_ml_tf2coreml/convert-mobilenet-model-to-coreml-tfcoreml.py:78: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
WARNING:tensorflow:From D:/WORK/Personal/Innaite/projects/matchpoint_ml_tf2coreml/convert-mobilenet-model-to-coreml-tfcoreml.py:78: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
WARNING:tensorflow:From C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tensorflow_core\python\tools\strip_unused_lib.py:88: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
WARNING:tensorflow:From C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tensorflow_core\python\tools\strip_unused_lib.py:88: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`

Loading the TF graph...
WARNING:tensorflow:From C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tfcoreml\_tf_coreml_converter.py:214: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tfcoreml\_tf_coreml_converter.py:214: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tfcoreml\_tf_coreml_converter.py:215: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

WARNING:tensorflow:From C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tfcoreml\_tf_coreml_converter.py:215: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

Graph Loaded.
Now finding ops in the TF graph that can be dropped for inference
Collecting all the 'Const' ops from the graph, by running it....
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: Node 'FeatureExtractor/MobilenetV2/Conv/BatchNorm/FusedBatchNormV3' (type: 'Add', num of outputs: 1) does not have output 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/WORK/Personal/Innaite/projects/matchpoint_ml_tf2coreml/convert-mobilenet-model-to-coreml-tfcoreml.py", line 109, in <module>
    image_scale=2. / 255)
  File "C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tfcoreml\_tf_coreml_converter.py", line 718, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tfcoreml\_tf_coreml_converter.py", line 327, in _convert_pb_to_mlmodel
    tensors_evaluated = sess.run(tensors, feed_dict=input_feed_dict)
  File "C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\ProgramData\Miniconda3\envs\ConvertTFModelToCoreML\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: Node 'FeatureExtractor/MobilenetV2/Conv/BatchNorm/FusedBatchNormV3' (type: 'Add', num of outputs: 1) does not have output 5
```

Any thoughts?

I have also seen this is basically the same with: https://github.com/tf-coreml/tf-coreml/issues/336

Thanks!

**Comment by bourdakos1** [comment]
I'm getting the same error
- tensorflow: 1.15.2
- coremltools: 3.3
- tfcoreml: 1.1

Conversion code:
```
tfcoreml.convert(
    tf_model_path='frozen_graph.pb',
    mlmodel_path='Model.mlmodel',
    input_name_shape_dict={input_tensor: [1, 300, 300, 3]},
    image_input_names='Preprocessor/sub:0',
    output_feature_names=['concat:0', 'Postprocessor/convert_scores:0'],
    is_bgr=False,
    red_bias=-1.0,
    green_bias=-1.0,
    blue_bias=-1.0,
    image_scale=2. / 255)
```

Frozen graph:
- [frozen_graph.pb](https://github.com/tf-coreml/tf-coreml/files/4360389/frozen_graph.pb.zip)

**Comment by bourdakos1** [comment]
@dlawrences Adding the following param to `tfcoreml.convert` resolved this issue for me
```
minimum_ios_deployment_target='13'
```

**Comment by dlawrences** [comment]
> @dlawrences Adding the following param to `tfcoreml.convert` resolved this issue for me
> 
> ```python
> minimum_ios_deployment_target='13'
> ```

Thanks @bourdakos1 , work for me as well!
