### ISSUE TITLE
AssertionError: Concat axis case not handled. output shape = [5733, 8], axis = 0

### ISSUE THREAD

**Issue by feifeiwei** [tf-coreml/tf-coreml#390]
My model produce error AssertionError: Concat axis case not handled.

1185/1190: Analysing op name: Reshape_2 ( type:  Reshape )
1186/1190: Analysing op name: concat ( type:  ConcatV2 )
Traceback (most recent call last):
  File "pb2coreml.py", line 22, in <module>
    minimum_ios_deployment_target='12')
  File "/Users/feifeiwei/anaconda3/envs/py36/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 718, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/Users/feifeiwei/anaconda3/envs/py36/lib/python3.6/site-packages/tfcoreml/_tf_coreml_converter.py", line 411, in _convert_pb_to_mlmodel
    convert_ops_to_layers(context)
  File "/Users/feifeiwei/anaconda3/envs/py36/lib/python3.6/site-packages/tfcoreml/_ops_to_layers.py", line 186, in convert_ops_to_layers
    translator(op, context)
  File "/Users/feifeiwei/anaconda3/envs/py36/lib/python3.6/site-packages/tfcoreml/_layers.py", line 119, in concat
    ss_layers._add_concat(op, context)
  File "/Users/feifeiwei/anaconda3/envs/py36/lib/python3.6/site-packages/tfcoreml/_shape_sensitive_layers.py", line 138, in _add_concat
    assert False, ('Concat axis case not handled. output shape = {}, axis = {}'.format(str(output_shape), axis))
AssertionError: Concat axis case not handled. output shape = [5733, 8], axis = 0

**Comment by 1duo** [comment]
Hi @feifeiwei, thanks for reporting the issue. Can you try out using `minimum_ios_deployment_target='13'` when call `convert()`? This allows to convert model using different path.
