### ISSUE TITLE
KeyError: u'classLabel' setting class_labels

### ISSUE THREAD

**Issue by lahayeg** [tf-coreml/tf-coreml#85]
Hi,

I follow tensorflow for poets sample. I want to create core ml with 2 outputs, classLabel and classLabelProbs. First step is to add in param my class label

import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'tf_files/optimized_graph.pb',
        mlmodel_path = 'tf_files/my_model.mlmodel',
        output_feature_names = ['final_result:0'],
        input_name_shape_dict = {'input:0':[1,224,224,3]},
        image_input_names = ['input:0'],
        red_bias = -1, 
        green_bias = -1, 
        blue_bias = -1, 
        image_scale = 2.0/255.0,
        class_labels  = 'tf_files/retrained_labels.txt')

But add got this issue:
420/420: Converting op name: final_result ( type:  Softmax )
Traceback (most recent call last):
  File "tfcoremlconverter.py", line 12, in <module>
    class_labels  = 'tf_files/retrained_labels.txt')
  File "/host/Desktop/workspace/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 478, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "/host/Desktop/workspace/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 354, in _convert_pb_to_mlmodel
    optimize_nn_spec(builder=builder)
  File "/host/Desktop/workspace/tf-coreml/tfcoreml/optimizations/_optimize_nn_spec.py", line 47, in optimize_nn_spec
    _optimize_disconnected_components(builder)
  File "/host/Desktop/workspace/tf-coreml/tfcoreml/optimizations/_optimize_nn_spec.py", line 37, in _optimize_disconnected_components
    _optimize._remove_disconnected_components(builder)
  File "/host/Desktop/workspace/tf-coreml/tfcoreml/optimizations/_optimize.py", line 355, in _remove_disconnected_components
    start_ids.append(blob_src[out.name])
KeyError: u'classLabel'

**Comment by lahayeg** [comment]
for classifier model, the classLabel output do not belonging to graph. That's why the node is not founded

**Comment by slin07** [comment]
@lahayeg Thank you for reporting this issue! We've identified the cause of this error. This is a bug in the converter where replacing ":" with "__" fails to include `labelProbabilityLayerName`. We're working on an update.

**Comment by slin07** [comment]
See PR#86

**Comment by slin07** [comment]
Is there any updates on this thread?
